### PR TITLE
explainer: Put the security section after the JS section

### PR DESCRIPTION
**Pull request by Kangz**
This was suggested by a Blink API owner in the "Intent to Experiement: WebGPU" thread in blink-dev. @kainino0x @kvark WDYT?

### CODE REVIEW

**Comment by kvark** [comment]
Any reasoning/justification for this?

**Comment by kainino0x** [comment]
> No worries! :) The explainer is great! Might be worthwhile to bump up the JS API part (maybe above the Privacy questionnaire part, to give folks a feeling of how the API is used before diving into the privacy and security details) 

https://groups.google.com/a/chromium.org/g/blink-dev/c/K4_egTNAvTs/m/WRI5ku84AgAJ

**Comment by kvark** [comment]
Ok, I don't have a problem with this, just curious

**Review by kainino0x — APPROVED** [review]

**Comment by Kangz** [comment]
Thanks!

**Comment by kainino0x** [comment]
> kainino0x self-requested a review 2 minutes ago

accidental

**Pull request merged**
