### PR TITLE
GPUBGLBinding: rename multisample to multisampled.

### PR DESCRIPTION
**Pull request by Kangz**
This is because reading binding.multisampled = false seems like better
grammar than binding.multisample.

***
<a href="https://pr-preview.s3.amazonaws.com/Kangz/gpuweb/pull/367.html" title="Last updated on Jul 15, 2019, 12:29 PM UTC (c24da29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/367/3d9b473...Kangz:c24da29.html" title="Last updated on Jul 15, 2019, 12:29 PM UTC (c24da29)">Diff</a>

### CODE REVIEW

**Comment by damyanp** [comment]
Possible out of scope for this review, but I'm a bit confused about when an app should specify "true" for this field.  Is this a promise about what the properties of the sampler that the shader might use to read from the texture?

**Comment by kvark** [comment]
@damyanp this is a promise that the shader sees this texture as an MSAA texture, and we are only able to create bind groups that have a multisampled texture filling this binding.

**Comment by damyanp** [comment]
@kvark - ah, I think I'm catching up.  Presumably this would be validated (in all implementations) so that if you try and bind a multisampled texture to a binding where the layout doesn't have this set then it would fail?

**Comment by kvark** [comment]
Yes, it should be validated along all the other fields of the bind group layout (by all implementations).

**Comment by kainino0x** [comment]
Rebased over #365

**Comment by Kangz** [comment]
Merging this as it is quite trivial.

**Pull request merged**
