### PR TITLE
Make arrayLayer and mipLevel naming consistent.

### PR DESCRIPTION
**Pull request by Kangz**
This is PR for what was discussed in #158

### CODE REVIEW

**Comment by kvark** [comment]
Thinking a bit some more, there is a semantic difference between "slice" and "array layer", and it comes into play when we start talking about cube textures. Say, you want to render into a side of a CubeArray texture. You'd want to select a slice there, not a layer of the array, given that each layer contains 6 slices.

**Comment by Kangz** [comment]
The cubeness is a property of the texture view and not of the texture view, so you'd always render to an array layer.

**Comment by Kangz** [comment]
@kainino0x that's correct, until the API supports 3D array texture but IIRC none of the native APIs have support for that.

**Comment by Kangz** [comment]
Thanks for the reviews, landing after a rebase for the WebGPU->GPU commit.

**Pull request merged**
