### PR TITLE
Add mix(vec, vec, f32) overload

### LINKED ISSUE #1588: Support mix(vec, vec, f32)
Spawned from https://github.com/gpuweb/gpuweb/issues/1520#issuecomment-809908102
In GLSL, you can say `mix(vec4(), vec4(), 0.5)`. Do we want WGSL to support this?

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1588

No strong feelings here. It seemed that there was an agreement to add it, hence I'm following up.

### CODE REVIEW

**Comment by ben-clayton** [comment]
Thumbs up from me.

**Comment by munrocket** [comment]
This will be very handy.

**Review by alan-baker — APPROVED** [review]

**Comment by ben-clayton** [comment]
Should we do the same for `smoothStep()` ?

**Comment by kvark** [comment]
It's similar for smoothstep, and an opposite in a way. The last parameter can be a vector if the first 2 parameters are scalars, which makes some sense, I suppose. I checked GLSL and HLSL, and they are fine. Haven't checked MSL.

**Pull request merged**
