### PR TITLE
[wgsl]: Add textureNum[Elements,Levels,Samples]

### PR DESCRIPTION
**Pull request by ben-clayton**

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
`textureNumElements` sounds a bit weird (e.g. compared to a possible `textureArraySize`), but I can see how this is preferred for consistency with the other methods you are adding here. LGTM

**Comment by ben-clayton** [comment]
> textureNumElements sounds a bit weird (e.g. compared to a possible textureArraySize), but I can see how this is preferred for consistency with the other methods you are adding here. LGTM

Yes, I agree. As I mentioned before, I'm not a fan of `size` due to its associations with memory size, and other alternatives were tediously long. Happy to rename if we can find something nicer.

**Comment by kvark** [comment]
Did you consider `textureNumLayers`?

**Comment by ben-clayton** [comment]
That works for me.

**Review by kvark — APPROVED** [review]

**Comment by ben-clayton** [comment]
Thanks!

**Pull request merged**
