### PR TITLE
wgsl tree-sitter: only invoke "npm install" when needed

### PR DESCRIPTION
**Pull request by dneto0**
This reduces: time, network traffic, and some amount of flakiness.

### CODE REVIEW

**Comment by greggman** [comment]
saw this go by and having dealt with this in personal projects was curious what solution was chosen.

As it is, if the package.json contains a newer version then won't this check skip over installing that newer version? Or maybe that is handled somewhere else?

**Review by mehmetoguzderin — APPROVED** [review]
LGTM, but the comment of @greggman is quite relevant. Personally, I fresh clone frequently, but I can see how this might evolve into a problem too. Though that could be brought into an external issue to track in another PR.

**Comment by dneto0** [comment]
I definitely chose the easy and imprecise solution.
The package.json file is written by the same extract-grammar.py script.  If someone updates the requested versions of those two files, I hope they remember to remove the directory too, so they get a fresh install.

Alternately, we could add command line flags.

**Comment by greggman** [comment]
I just wanted to pass on a solution I've used which is here

https://github.com/greggman/ld-check-dependencies/blob/master/index.js

It basically calls `npm install --dry-run --json` and checks to see if anything would have been added or changed.

The problem I've run into with it is if I'm doing dev with `npm link` then it will claim something will be updated and so I've had to add options to skip the check.

**Pull request merged**
