### PR TITLE
Reserve -- and ++

### PR DESCRIPTION
**Pull request by dneto0**
Fixes: #801

### CODE REVIEW

**Comment by jdashg** [comment]
`a--3` still ok?

**Comment by dneto0** [comment]
> a--3 still ok?

No, because tokens are parsed greedily.  So the tokens would be:

     a
     --
     3

If you want to subtract -3 from a, write  either:
  

     a-(-3)

or

     a- -3


Related: I've been working offline and think I have the heart of a good solution for the MIN_INT problem.

**Comment by dj2** [comment]
I don't think we could split the `--` in this case as you don't know if the user wanted `(a--) <something> x` or `a <something> --x` or `a - -x`. There isn't enough context here to do it safely if we want to allow `--` in the future.

**Review by dj2 — APPROVED** [review]

**Comment by kvark** [comment]
I have a little concern that people will come to us and ask to make those operators real... since we reserved them anyway.

As for `--x` case, I remember we discussed operator precedence (see #1111), and that we should make it *required* for some operators to be combined used parethesis (like "Require parenthesis" in https://github.com/gpuweb/gpuweb/pull/1111#issuecomment-705039742). So... wouldn't the problem with `--x` be trivially solved by just requiring the parentheses for combining unary `-` and `+` operators? In this case we'd be better off without reserving these extra tokens.

**Comment by litherum** [comment]
re: @kvark, I still think we should reserve these tokens anyway. Just in case.

**Review by litherum — APPROVED** [review]

**Comment by dneto0** [comment]
Discussed [2021-03-09](https://docs.google.com/document/d/1IQLS_nypwJLjaMZlejMSMC_vP7D2pm0EH1NtZ1TIvs0/edit#heading=h.a0fpht4tpxjd)

Approved.

**Pull request merged**
