### PR TITLE
Remove textureGather on integer textures

### LINKED ISSUE #4841: `textureGather` with integer texture formats doesn't work on AMD devices
Posting this to see if we want to consider it just an AMD bug or spec change worthy (like say, disallowing uint/sint texture formats and textureGather with cubemaps

The setup is. Given an 8x8 cube map (so 6 layers). The texture coordinate is `-0.7084864819326223, 0.705718956612574, 0.002767525320049306`

That coordinate gets converted to face index and a texel. The face index is (1) so the (-x face). The texel coordinate is `4.016, 0.016`.  

x = 4.016 means it's just past the 5th texel in X  (0-1 is the first texel, 1-2 is the second texel, .... 4-5 is the 4th texel). 

y = 0.016 means it's just under the top edge (or above the bottom depending on your POV)

```
              x = 4.016
                 |
                 V
+---+---+---+---+---+---+---+---+ ◢___ y = 0.016 
|   |   |   |   |   |   |   |   | 
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
```

Given that the texel coordinate is in the top left corner of the texel, this square represents the texels that should be "gathered"

```
            ╔═══╦═══╗
            ║ A ║ B ║
┌───┬───┬───╫═══╬═══╫───┬───┬───┐
│   │   │   ║ R ║ G ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
└───┴───┴───┴───┴───┴───┴───┴───┘
```

A and B are from a different face of the cube. This is what I see on several GPUs. 

But on AMD (Mac and Linux, don't have access to AMD windows) I see this

```
┌───┬───┬───╦═══╦═══╦───┬───┬───┐
│   │   │   ║ A ║ B ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   ║ R ║ G ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
└───┴───┴───┴───┴───┴───┴───┴───┘
```

In order for that to happen, y would have to be >= 0.5 but y is 0.016

Also, this issue happens for integer texture formats, not floating point or unorm formats.

You can test here: https://jsgist.org/?src=f32cd47fd0cb0e8330c1c54a44cc9f74

Correct results look like this

```
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4099,4100,8448,8384
R gather = F1:X3:Y0, F1:X4:Y0, F2:X0:Y4, F2:X0:Y3
+----+----+----+----+----+----+----+----+
|    |    |    | R1 | G1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| A2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| B2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

R1 = red component contained texel(3,0) from layer 1 (-x face)
A2 = alpha component contained texel(0,3) from layer 2 (+y face)

Anything else is bad. 

On Linux AMD I see this

```
amd gcn-4
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4163,4164,4100,4099
R gather = F1:X3:Y1, F1:X4:Y1, F1:X4:Y0, F1:X3:Y0
+----+----+----+----+----+----+----+----+
|    |    |    | A1 | B1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    | R1 | G1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

On Mac AMD I see this

```
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4096,4097,4097,4096
R gather = F1:X0:Y0, F1:X1:Y0, F1:X1:Y0, F1:X0:Y0
+----+----+----+----+----+----+----+----+
| A1 | B1 |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

This is missing R and G because they returned the same texel (same or different face) and the diagram maker only shows the one result per texel location.

# This also fails on Mac AMD for 2D textures

Example:

https://jsgist.org/?src=fd8b1728e4eae2bcc29f515d068521c0

Mac M1 / Mac Intel / Linux AMD (correct)

```
uv coord   : 0.4, 0.2
texel coord: 3.2, 1.6
result[0] = 130,131,67,66
R gather = F0:X2:Y2, F0:X3:Y2, F0:X3:Y1, F0:X2:Y1
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    | A0 | B0 |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    | R0 | G0 |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

Mac AMD

```
amd rdna-1
uv coord   : 0.4, 0.2
texel coord: 3.2, 1.6
result[0] = 0,0,0,0
R gather = F0:X0:Y0, F0:X0:Y0, F0:X0:Y0, F0:X0:Y0
+----+----+----+----+----+----+----+----+
| A0 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

* We could just mark this as an AMD bug.
* We could see that it's not portable and decide to disallow uint/sint formats with `textureGather`
* We could try to workaround it.

  For cubemaps, I think you can take the cube coord, convert to face coord, quantize with `ceil`/`floor` to get 4 face coords, convert back to cube coords, then call `textureSampleLevel` on each of the 4 coords. You'd need further quantize the coordinates to make sure you got texel centers so as to ignored sampler settings (nearest, linear).
  
  For 2d it's similar just skip the cube->face->cube converts.

* other...?

### PR DESCRIPTION
**Pull request by kainino0x**
Fixes #4841 - see there for info

Chromium currently exposes this, so the plan is to go through a deprecation process to make sure we know about any current usage in the wild. https://crbug.com/370059107

### CODE REVIEW

**Comment by JMS55** [comment]
Bevy uses this for our SSAO denoiser :/ https://github.com/bevyengine/bevy/blob/c32e0b9ec226cb5004dc44a89ea675a9e7728bb1/crates/bevy_pbr/src/ssao/spatial_denoise.wgsl#L26

**Comment by greggman** [comment]
@JMS55
 
Have you tried this code on AMD devices? My tests seem to indicate no AMD devices support this.

Given that, it seems the best we can do is add it back as a feature. But if you want your code to run on AMD devices you'll need to find a solution that doesn't use the feature.

**Comment by JMS55** [comment]
I have not personally, but users have used SSAO on AMD devices and if there's artifacts, they've not be noticeable enough to matter. I guess we can switch to 4 manual texture loads.

**Comment by greggman** [comment]
Do you have a link to an example and that uses SSAO with integer formats? I'd be curious to try it.

**Comment by JMS55** [comment]
Clone https://github.com/bevyengine/bevy, and run `cargo run --example ssao --release`.

**Comment by greggman** [comment]
thanks. I would need a webpage version which I couldn't figure out how to build. I have zero experience with rust. I found [this](https://github.com/bevyengine/bevy/issues/9618) but there are 50+ Cargo.toml files. I tried putting in the top one but just got errors amount missing dependencies. Maybe you could add the SSAO example to your live webpgu samples page?

**Comment by JMS55** [comment]
Unfortunately our SSAO code doesn't run on WebGPU in browsers atm, due to (last time I checked) R16Float textures not supporting storage binding, and max_storage_textures_per_shader_stage being too low in the minimum possible limits.

**Review by alan-baker — CHANGES_REQUESTED** [review]
I think it would be better to just move the sample type out of the preconditions and embed f32 in the overload (e.g. similar to coords).

**Comment by Kangz** [comment]
The reason why we have to disable sint/uint texture for sure, is that textureGather on stencil can be helplessly broken on some devices, and that we can't polyfill for `texture_cube[_array]<u32>` due to the lack of `textureLoad` for them. Maybe we could just disable cube uint/sint textures and polyfill on devices where we know uint/sint is bad for stencil?

Or make it a feature that bevy would have to explicitly request, like R16Float textures.

**Review by dneto0 — APPROVED** [review]
LGTM from editorial perspective.

**Comment by greggman** [comment]
So I'm going through the tests again and I just want to re-iterate. This function doesn't work on AMD Mac.

I'd be interested to know, @JMS55, if you can check an AMD Mac in particular with your code tha uses this feature. You mentioned you didn't see any artifacts but to me that suggests that maybe whatever you expect to see is not what you're seeing? 

Here's an example of what I mean by "does not work". From some tests:

```
  - EXPECTATION FAILED: subcase: C="i32";samplePoints="texel-centre"
    result was not as expected:
          size: [8, 8, 1]
      mipCount: 3
          call: textureGather(component: i32(1), texture: T, sampler: S, coords: vec2f(0.21875, 0.46875))  // #0
              : as texel coord @ mip level[0]: (1.750, 3.750)
              : as texel coord @ mip level[1]: (0.875, 1.875)
              : as texel coord @ mip level[2]: (0.438, 0.938)
           got: 30, 30, 30, 30
      expected: 207, 138, 139, 91
      max diff: 0
     abs diffs: 177, 108, 109, 61
     rel diffs: 85.51%, 78.26%, 78.42%, 67.03%
     ulp diffs: 177, 108, 109, 61
    
      sample points:
    expected:                                                                             | got:
                                                                                          | 
    layer: 0                                                                              | layer: 0 
        0   1   2   3   4   5   6   7                                                     |     0   1   2   3   4   5   6   7 
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    0 |   |   |   |   |   |   |   |   |                                                   | 0 | a |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    1 |   |   |   |   |   |   |   |   |                                                   | 1 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    2 |   |   |   |   |   |   |   |   |                                                   | 2 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    3 |   | a | b |   |   |   |   |   |                                                   | 3 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    4 |   | c | d |   |   |   |   |   |                                                   | 4 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    5 |   |   |   |   |   |   |   |   |                                                   | 5 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    6 |   |   |   |   |   |   |   |   |                                                   | 6 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    7 |   |   |   |   |   |   |   |   |                                                   | 7 |   |   |   |   |   |   |   |   |
      +---+---+---+---+---+---+---+---+                                                   |   +---+---+---+---+---+---+---+---+
    a: mip(0) at: [ 1,  3,  0], weights: [R: 0.00000, G: 0.00000, B: 0.00000, A: 1.00000] | a: mip(0) at: [ 0,  0,  0], weight: 1.00000
    b: mip(0) at: [ 2,  3,  0], weights: [R: 0.00000, G: 0.00000, B: 1.00000, A: 0.00000] | a: value: R: 0.00000, G: 0.00000, B: 0.00000, A: 0.00000
    c: mip(0) at: [ 1,  4,  0], weights: [R: 1.00000, G: 0.00000, B: 0.00000, A: 0.00000] | level weight: 1.00000
    d: mip(0) at: [ 2,  4,  0], weights: [R: 0.00000, G: 1.00000, B: 0.00000, A: 0.00000] | 
    a: value: R: 246.00000, G: 91.00000, B: 165.00000, A: 61.00000                        | 
    b: value: R: 237.00000, G: 139.00000, B: 168.00000, A: 166.00000                      | 
    c: value: R: 251.00000, G: 207.00000, B: 147.00000, A: 200.00000                      | 
    d: value: R: 4.00000, G: 138.00000, B: 180.00000, A: 84.00000                         | 
    
    
```

You can see above it's a simple call. We pass in `vec2f(0.21875, 0.46875)` as the coordinate. On the left is the correct samples. On the right is what was actually sampled. Just the top left corner.

You can run the test yourself [here](https://gpuweb.github.io/cts/standalone/?debug=1&runnow=1&q=webgpu:shader,execution,expression,call,builtin,textureGather:sampled_2d_coords:stage=%22v%22;format=%22rgba8uint%22;filt=%22nearest%22;modeU=%22r%22;modeV=%22c%22;offset=false). This link though may disappear soon as we'll filter out these tests assuming we continue with the decision to remove this support.

You can change the format by editing `format="rgba8uint"` in the URL to another uint/sint format.

Note: They appear to work on AMD Linux Vulkan

**Comment by JMS55** [comment]
I don't have an AMD mac to test on, but I asked if any Bevy uses could try SSAO and see if it looks broken.

If you have a test that shows textureGather is broken in this case though, then it's fine to remove it, we'll figure something else out.

**Comment by JMS55** [comment]
Looks like we don't have any users with AMD macs around to test this.

**Pull request closed without merging**
