### PR TITLE
Fix bikeshed error: N used only once in algorithm

### PR DESCRIPTION
**Pull request by dneto0**
This still renders the same.

### CODE REVIEW

**Review by kvark — APPROVED** [review]
somewhat unfortunate to have this inconsistent with other cases where N is used

**Comment by dj2** [comment]
The other option is to add N to the ignored vars at the top. I did that for a bunch of the 'e' vars until we add spec text for the stdlib methods.

**Comment by dneto0** [comment]
> The other option is to add N to the ignored vars at the top. I did that for a bunch of the 'e' vars until we add spec text for the stdlib methods.

I'll do that as soon as I figure out how.

**Comment by dneto0** [comment]
PTAL.

**Review by kvark — APPROVED** [review]

**Review by dj2 — APPROVED** [review]

**Pull request merged**
