### PR TITLE
Add texture sample function which clamps coordinates

### LINKED ISSUE #2766: Specify that texture_external sampling functions clamp coords to [0, 1]
This is because in browsers in general the video might have data around it that's unrelated to the video. The injected shader might be doing a transform on the coord to select a potentially non-aligned rectangle of the video frame. The injected shader does a transform that maps the [0, 1]^2 range correctly, but values outside of that range may be sampling outside of the sub-rectangle of the video frame. To prevent this we can specify that the operations always clamp to [0, 1]^2

### PR DESCRIPTION
**Pull request by kainino0x**
Adds this function for both texture_2d and texture_external for
symmetry as agreed in discussion.

Name up for bikeshedding, but this is my proposal.

Fixes #2766

### CODE REVIEW

**Comment by kainino0x** [comment]
> Name up for bikeshedding, but this is my proposal.

LOD naming:
- Level: makes it sound like you're going to pass a level
- Base: IMO a bit clearer because it uses the "base" of the texture view

clamping naming:
- Clamp, Clamped: sounds like clamping the LOD
- Clamped, Clamp01: sounds like clamping the output of the sampling operation
- ClampToEdge: matches the language used in the API (`"clamp-to-edge"`)

**Review by toji — APPROVED** [review]
I think it was Winston Churchill who said "textureSampleBaseClampToEdge is the worst name for a function – except for all the others that have been considered."

LGTM.

**Review by dneto0 — APPROVED** [review]
LGTM with nit for removing a sentence.

**Comment by kainino0x** [comment]
@litherum PTAL

**Review by dneto0 — APPROVED** [review]
Thanks!

**Comment by dneto0** [comment]
Approved in WGSL meeting 2022-09-13.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-13-minutes#add-texture-sample-function-which-clamps-coordinates-3403">WGSL 2022-09-13 Minutes</a></summary>

* **Resolved: Accept**


</details>

**Pull request merged**
