### PR TITLE
Allow postfixes in the assignment lhs

### LINKED ISSUE #719: [wgsl] Describe the assignment statement
The WGSL standard should add a section fully describing the syntax and semantics of the assignment statement.

No such section exists right now.

The grammar has a rule called `assignment_stmt`:
```
assignment_stmt
  : primary_expression EQUAL logical_or_expression
```
This grammar allows `foo = 42`, and it allows `17 = 42`, as legal assignment statements. However, it does not allow `a[i] = 42` or `a.foo = 42`.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #719

### CODE REVIEW

**Comment by kvark** [comment]
Good observation, @jdashg ! Fixed now

**Comment by dneto0** [comment]
This seems right as far as being a fix on the grammar line.

The explanatory text below the grammar line is wrong.
Currently:

```
      If primary_expression is a variable
       OpLoad
      If primary_expression is a const, this is just an assignment the ssa var
```

First, `primary_expression` is no longer the right term.

Second, OpLoad should have been OpStore.

_At most_ it should read:
```
      If singular_expression is a variable, this maps to OpStore to the variable
      Otherwise, singular expression is a pointer expression in an Assigning (L-value) context which maps to OpAccessChain followed by OpStore
```
But maybe we should have a proper MR to explain how variable-assignment actually works.

**Comment by kvark** [comment]
Thanks @dneto0 ! I missed that, now replaced that section with the exact wording you provided.

**Comment by grorg** [comment]
It looks like this is ready to merge. pinging @dneto0 and @jdashg to confirm they are happy with the updates.

**Comment by dj2** [comment]
I think this is good to go, all comments have been addressed. Merging.

**Pull request merged**
