### PR TITLE
webgpu favicon

### PR DESCRIPTION
**Pull request by dcerisano**
Created webgpu.ico from webgpu.svg
Multipart ico with sizes from 16x16 to 256x256

### CODE REVIEW

**Comment by mehmetoguzderin** [comment]
@dcerisano thank you for producing the favicon. It could be good to incorporate within spec as Bikeshed supports Favicon [^1] as long as it is acceptable procedurally (since these specs gets published to W3C). I'm not leaving a review as I'm not very closely familiar with multipart ico format's header, but in case other editors are busy, I might get back to make sure we have an nearly-optimally small binary file in repo (or can we make this file produced through Python to just go into GH Pages by root of out/?).

[^1]: https://speced.github.io/bikeshed/#metadata-favicon

**Comment by dcerisano** [comment]
Thanks, I see it got moved to "Milestone 0".
Created it for personal use, thought I would just leave it here.
It is public domain, actually hope the WebGPU logo undergoes a few more
iterations - it's almost there but kinda squidgy at low res.

*Dominic Cerisano*

***@***.***



NOTICE: Confidential message which may be privileged. Unauthorized
use/disclosure prohibited.
AVIS : Message confidentiel dont le contenu peut être privilégié.
Utilisation/divulgation interdites sans permission.

**Comment by mehmetoguzderin** [comment]
Dear @dcerisano ,

Thank you very much for sharing the file once again. I have created a PR in your fork with following changes: reduce file size and rename to webgpu-notext.ico to match original. When the frames of ICO are quantized, the output reduces to 8KB from 196KB (or to 6KB from 192KB by the Web UI of GitHub). Output looks as follows:

webgpu-notext-summary

I have found that it is quite tricky to make an ICO which preserves palette properly, using append_images in Pillow produced a nicer header and preserve sizes for ICO rather than ImageMagick. Following is the output from `webgpu.ico` (`identify webgpu.ico` of ImageMagick):

```
webgpu.ico[0] ICO 16x16 16x16+0+0 8-bit sRGB 0.000u 0:00.006
webgpu.ico[1] ICO 24x24 24x24+0+0 8-bit sRGB 0.000u 0:00.007
webgpu.ico[2] ICO 32x32 32x32+0+0 8-bit sRGB 0.000u 0:00.007
webgpu.ico[3] ICO 48x48 48x48+0+0 8-bit sRGB 0.000u 0:00.007
webgpu.ico[4] ICO 64x64 64x64+0+0 8-bit sRGB 0.000u 0:00.006
webgpu.ico[5] ICO 72x72 72x72+0+0 8-bit sRGB 0.000u 0:00.006
webgpu.ico[6] ICO 80x80 80x80+0+0 8-bit sRGB 0.000u 0:00.006
webgpu.ico[7] ICO 96x96 96x96+0+0 8-bit sRGB 0.000u 0:00.006
webgpu.ico[8] ICO 128x128 128x128+0+0 8-bit sRGB 0.000u 0:00.005
webgpu.ico[1] PNG 256x256 256x256+0+0 8-bit sRGB 196862B 0.000u 0:00.002
```

Following is `webgpu-notext.ico`:

```
webgpu-notext.ico[0] PNG 16x16 16x16+0+0 8-bit sRGB 263B 0.000u 0:00.002
webgpu-notext.ico[1] PNG 24x24 24x24+0+0 8-bit sRGB 307B 0.000u 0:00.001
webgpu-notext.ico[2] PNG 32x32 32x32+0+0 8-bit sRGB 342B 0.000u 0:00.001
webgpu-notext.ico[3] PNG 48x48 48x48+0+0 8-bit sRGB 380B 0.000u 0:00.001
webgpu-notext.ico[4] PNG 64x64 64x64+0+0 8-bit sRGB 446B 0.000u 0:00.000
webgpu-notext.ico[5] PNG 72x72 72x72+0+0 8-bit sRGB 486B 0.000u 0:00.000
webgpu-notext.ico[6] PNG 80x80 80x80+0+0 8-bit sRGB 533B 0.000u 0:00.000
webgpu-notext.ico[7] PNG 96x96 96x96+0+0 8-bit sRGB 583B 0.000u 0:00.000
webgpu-notext.ico[8] PNG 128x128 128x128+0+0 8-bit sRGB 770B 0.000u 0:00.000
webgpu-notext.ico[9] PNG 256x256 256x256+0+0 8-bit sRGB 5794B 0.000u 0:00.000
```

I was able to produce this file using following Python script (not a polished one). First command:

```
python3 svg-and-palette-ico.py svg2ico https://raw.githubusercontent.com/gpuweb/gpuweb/main/logo/webgpu-notext.svg webgpu-notext.svg
```

And the script:

```
import re
import cairosvg
import requests
from PIL import Image
from xml.etree import ElementTree as ET
import argparse


def download_svg_from_url(url, save_path):
    response = requests.get(url)
    with open(save_path, "wb") as file:
        file.write(response.content)
    return save_path


def hex_to_rgb(value):
    value = value.lstrip("#")
    result = [0, 0, 0, 255]
    length = len(value)
    for index, i in enumerate(range(0, length, length // 3)):
        result[index] = int(value[i : i + length // 3], 16)
    return tuple(result)


def next_power_of_two(n):
    # Find the next power of two
    p = 1
    while p < n:
        p <<= 1
    return p


def get_next_power_of_two(n):
    # Find the next power of two
    p = next_power_of_two(n)
    # Get the next power of two
    return p << 1


# Generate number of palette colors by finding colors in SVG, adding empty transparent, and getting next power of two
def extract_colors_from_svg(svg_file):
    with open(svg_file, "r") as file:
        content = file.read()
    colors = re.findall(r"#[0-9a-fA-F]{6}", content)
    unique_colors = list(set(colors))
    unique_colors = [hex_to_rgb(color) for color in unique_colors]
    unique_colors.append((0, 0, 0, 0))
    return min(256, get_next_power_of_two(len(unique_colors)))


def rasterize_svg_with_palette(svg_file, palette):
    # Parse the SVG file to extract its width and height
    tree = ET.parse(svg_file)
    root = tree.getroot()
    width = float(root.attrib.get("width", "0").replace("px", ""))
    height = float(root.attrib.get("height", "0").replace("px", ""))

    # Calculate padding to make it square
    if width > height:
        padding = (width - height) / 2
        new_viewbox = f"{root.attrib['viewBox']} -{padding} {width} {width}"
        root.attrib["viewBox"] = new_viewbox
        root.attrib["height"] = f"{width}px"
    elif height > width:
        padding = (height - width) / 2
        new_viewbox = f"-{padding} {root.attrib['viewBox']} {height} {height}"
        root.attrib["viewBox"] = new_viewbox
        root.attrib["width"] = f"{height}px"

    # Convert modified SVG tree back to a string
    modified_svg = ET.tostring(root, encoding="unicode")

    # Rasterize the modified SVG to PNG
    png_output = svg_file.replace(".svg", ".png")
    cairosvg.svg2png(
        bytestring=modified_svg.encode("utf-8"),
        write_to=png_output,
        output_width=2048,
        output_height=2048,
    )
    with Image.open(png_output) as im:
        # im = im.resize((256, 256))
        im = im.convert("RGBA")
        im = im.quantize(colors=palette)
        im.save(png_output)
    return png_output


def downsample_and_create_ico(png_file, palette, sizes):
    with Image.open(png_file) as im:
        im = im.convert("RGBA")
        ico_output = png_file.replace(".png", ".ico")
        images = [im.resize((i, i)).quantize(colors=palette, method=2) for i in sizes]
        images[-1].save(
            ico_output,
            format="ICO",
            sizes=[(i, i) for i in sizes],
            append_images=images,
        )
        icons = images
        total_width = sum(icon.width for icon in icons)
        max_height = max(icon.height for icon in icons)
        combined_image = Image.new("RGBA", (total_width, max_height))
        x_offset = 0
        for icon in icons:
            combined_image.paste(icon, (x_offset, 0))
            x_offset += icon.width
        combined_image.save(png_file.replace(".png", "-summary.png"))


def downsample_png(png_file, palette, sizes):
    with Image.open(png_file) as im:
        for i in sizes:
            im.resize((i, i)).quantize(colors=palette, method=2).save(
                png_file.replace(".png", f"-{i}.png")
            )
            im.resize((i, i)).quantize(colors=palette, method=2).save(
                png_file.replace(".png", f"-{i}.ico"), format="ICO", sizes=[(i, i)]
            )


def combine_icons_from_ico(ico_path, output_path):
    ico = Image.open(ico_path)
    icons = [ico.seek(index).copy() for index in range(len(ico.info.get("sizes")))]
    total_width = sum(icon.width for icon in icons)
    max_height = max(icon.height for icon in icons)
    combined_image = Image.new("RGBA", (total_width, max_height))
    x_offset = 0
    for icon in icons:
        combined_image.paste(icon, (x_offset, 0))
        x_offset += icon.width
    combined_image.save(output_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Utility for SVG and ICO processing.")
    subparsers = parser.add_subparsers(dest="command")

    # SVG Processing command
    svg_parser = subparsers.add_parser("svg2ico", help="Convert SVG to ICO.")
    svg_parser.add_argument("url", type=str, help="URL of the SVG file to download.")
    svg_parser.add_argument(
        "save_path", type=str, help="Local path to save the SVG file."
    )

    # ICO Processing command
    """ ico_parser = subparsers.add_parser(
        "combineico", help="Combine icons from ICO into a preview."
    )
    ico_parser.add_argument("ico_path", type=str, help="Path to the ICO file.")
    ico_parser.add_argument(
        "output_path", type=str, help="Output path for combined icons."
    ) """

    args = parser.parse_args()

    if args.command == "svg2ico":
        svg_path = download_svg_from_url(args.url, args.save_path)
        palette = extract_colors_from_svg(svg_path)
        png_file = rasterize_svg_with_palette(svg_path, palette)
        downsample_and_create_ico(
            png_file, palette, [16, 24, 32, 48, 64, 72, 80, 96, 128, 256]
        )
    # elif args.command == "combineico":
        # combine_icons_from_ico(args.ico_path, args.output_path)
    else:
        parser.print_help()
```

**Comment by Kangz** [comment]
Thanks @dcerisano and @mehmetoguzderin for pushing this! The ICO files looks good. Let's use the smaller one that's palettized and 6KB.

**Comment by dcerisano** [comment]
Noticed that  Mehmet's pallete was too small for this 5 colour icon and lost a color or two.

- Used GIMP to quantize (png compression) and palettize (5 color index).
- Also only included common icon sizes. 
- New webgpu.ico preserves all colours and is only 5.7Kb in size.

image

**Comment by mehmetoguzderin** [comment]
The palette issue was a small problem with my local environment quantizing incorrectly, I've done a hotfix by generating in Codespaces. Main's webgpu-notext.ico is now as follows:

webgpu-notext-summary

**Comment by toji** [comment]
The latest output that @mehmetoguzderin posted LGTM! And I'll repeat what I told him on a call just now: I don't mind any quantization that needs to be done if the result is a smaller file. I don't consider any aspect of the design immutable as long as it's recognizable as the same symbol and the triangle size ratios are pretty close. Even the colors are OK to fudge a bit, as I didn't have any specific artistic intent besides starting with W3C blue and getting lighter as the triangles get smaller.

The biggest thing I would look out for is ensuring there's no hairline gaps between the triangles (my first SVG had this problem) and that the color of each triangle is distinct enough that they all read as separate shapes. And again, the latest version in this thread seems to satisfy that.

**Comment by mehmetoguzderin** [comment]
@toji Thank you very much for your review of the rendering from your beautifully designed logo which serves the eye with good distinguishing factor even when we resize to extremely small resolutions. As that version with all .ico sizes (which just makes only 1-1.5KB difference, not a gap like 200KB vs 6KB) are in the main already, I think we can close the PR. @dcerisano , thank you very much for the suggestion.

**Pull request closed without merging**
