### PR TITLE
Officially add Brandon as a spec editor

### PR DESCRIPTION
**Pull request by kainino0x**
Brandon has de facto equal standing as an editor and I think it's time to recognize it.

***
<a href="https://pr-preview.s3.amazonaws.com/kainino0x/gpuweb/pull/2418.html" title="Last updated on Dec 16, 2021, 12:47 AM UTC (fbc4511)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/2418/eb39ff6...kainino0x:fbc4511.html" title="Last updated on Dec 16, 2021, 12:47 AM UTC (fbc4511)">Diff</a>

### CODE REVIEW

**Review by Kangz — APPROVED** [review]
LGTM, but I'd also like @jdashg's approval since IIRC the W3C rules are that "chairS nominate editors"

**Review by kvark — APPROVED** [review]
I was just thinking about this the other day.

**Comment by Kangz** [comment]
@jdashg ping!

**Review by kdashg — APPROVED** [review]

**Comment by kdashg** [comment]
Thanks for the ping!

**Pull request merged**
