### PR TITLE
[wgsl] Remove the preamble section

### PR DESCRIPTION
**Pull request by dj2**
This CL removes the preamble section from the spec, the generated SPIR-V in this
case is an implementation detail. The Vulkan Memory Model is explicitly called out
as what we are following.

***
<a href="https://pr-preview.s3.amazonaws.com/dj2/gpuweb/pull/1177.html" title="Last updated on Nov 10, 2020, 2:30 PM UTC (de16efa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/1177/7a3f41b...dj2:de16efa.html" title="Last updated on Nov 10, 2020, 2:30 PM UTC (de16efa)">Diff</a>

### CODE REVIEW

**Review by dneto0 — APPROVED** [review]

**Comment by dj2** [comment]
Wasn't sure if this needed to go through the group as it's just changing the SPIR-V representation. Is this good to merge, or should we wait?

**Comment by grorg** [comment]
Discussed at [2020-11-03 meeting](https://docs.google.com/document/d/1oV6pmwFOcomeuInQRl-erFt6ZiQfApXYSjoJis7zetA/).

**Comment by grorg** [comment]
Resolution: Don't accept in this form. @dj2 to update the PR to remove the preamble, and keep using the Vulkan Memory Model (without acquire/release).

**Comment by dj2** [comment]
PTAL.

**Comment by dj2** [comment]
I don't know what GitHub has done here, I'm going to close and create a new PR.

**Pull request closed without merging**
