### PR TITLE
For e.g. GPUOrigin2D, accept either dict or sequence.

### PR DESCRIPTION
**Pull request by jdashg**
Alternative to #299.

### CODE REVIEW

**Comment by grovesNL** [comment]
It seems better to only expose one of these variations for consistency – users will naturally tend towards one of these anyway.

Personally I don't mind some verbosity here (I think the explicitness is useful) so I prefer the dict approach. But I think I'd still prefer the sequence alternative over having both.

**Comment by kvark** [comment]
In agreement with @grovesNL , I'm also wondering what this dichotomy is going to look like in a C header?

**Comment by jdashg** [comment]
The C header is not bound by the ergonomic choices of the WebIDL.

**Comment by kainino0x** [comment]
I agree, I think in C always using a struct here would be fine. Inline initialization would look the same as an array (`{0, 0, 0, 0}`) in C/C++.

**Comment by jdashg** [comment]
Agreed on the 2019June17 call.

**Pull request merged**
