### PR TITLE
Issue 1534's array types differ on stride

### PR DESCRIPTION
**Pull request by dneto0**
This builds on #1792, and is really only the last commit in the chain.

### CODE REVIEW

**Comment by dneto0** [comment]
This would resolve the only current case for #1534

**Review by kvark — COMMENTED** [review]
last commit LGTM

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-08-10-Minutes#issue-1534s-array-types-differ-on-stride-1943">WGSL meeting minutes 2021-08-10</a></summary>



* [Deferred until this week. Google needs more internal discussion]
* Tabled indefinitely, Google to revive discussion when ready


</details>

**Comment by dneto0** [comment]
Closing, since the stride of an array only depends on its element type.
The stride attribute was removed. #2503

**Pull request closed without merging**
