### PR TITLE
Separate loadOp and clear values

### LINKED ISSUE #1377: Reconsider GPULoadOp "clear"/"zero"
It was decided in #283 not to duplicate the functionality of `loadValue: [0, 0, 0, 0]` with a `loadValue: "zero"` or similar.

However, in the time since then, I've seen numerous users trip up on this, using `loadValue: "load"` when it's not necessary, because doing the simpler thing seems like it should be the "better" thing.
Of course, [EDIT: **if** in the same command buffer or on a late-recording implementation] `loadValue: "load"` gets replaced with `loadValue: [0, 0, 0, 0]` if the render target happened to be in an uninitialized state before the render pass, so in many cases it's not actually a pessimization. But I think we should make the "fast" option more accessible.

### PR DESCRIPTION
**Pull request by toji**
Fixes #1377.
Split out from #2371.

Flattens out the attachment loadOp/clearValue and gives the clear values defaults. This should address concerns that developers may pick a potentially less efficient path (`"load"`) simply because it's easier to type. Instead they can use `"clear"` to clear to the default value (zeros) and specify a different clear value if one is needed.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 14, 2021, 9:15 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgpuweb%2Fgpuweb%2Fae5c97f8d7484b6b4177a7cfdddca7a02e10a97b%2Fspec%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20gpuweb/gpuweb%232386.)._
</details>

***
<a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/pull/2386.html" title="Last updated on Jan 25, 2022, 12:56 AM UTC (b65c38e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/2386/89b0dba...b65c38e.html" title="Last updated on Jan 25, 2022, 12:56 AM UTC (b65c38e)">Diff</a>

### CODE REVIEW

**Review by kainino0x — COMMENTED** [review]
PR LGTM, but I think we'll want to talk about this change outside of the editors group.

**Review by kvark — APPROVED** [review]

**Comment by kainino0x** [comment]
> PR LGTM, but I think we'll want to talk about this change outside of the editors group.

(To be clear, I am definitely in favor of the change.)

**Comment by rcelyte** [comment]
> a potentially less efficient path (`"load"`)

Really? In my experience (in Chrome) using `"load"` resulted in a 20% or more speedup compared to setting a clear color.

**Comment by kainino0x** [comment]
@rcelyte what OS and GPU? Surprised to see differences that large although I can believe it. Would be great if you have a test case.

The guidance is unfortunately not universal but a tradeoff. I expected to see very small penalties to "clear" on most desktop GPUs but large penalties to "load" on mobile GPUs (but Chrome doesn't have mobile GPU support yet except I think on Mac M1).

**Comment by rcelyte** [comment]
> @rcelyte what OS and GPU?

Manjaro Linux, RX 580

My benchmark simply iterates over a 64x32 grid of viewports, rendering fullscreen quads in each via the sequence below:
```
wgpuCommandEncoderBeginRenderPass()
wgpuRenderPassEncoderSetViewport()
wgpuRenderPassEncoderExecuteBundles()
wgpuRenderPassEncoderEndPass()
```
Using `Load` averages ~8.23ms per frame while `Clear` averages ~10.07ms.
It isn't the most scientific test, but the results are definitive.

Also, I doubt it's significant, but I'd be curious to know how much my WASM->Javascript binding is influencing this, given the dynamic typing involved with the current interface:
```js
loadValue: /*WGPURenderPassColorAttachment.loadOp*/ ? 'load' : {
	r: /*WGPURenderPassColorAttachment.clearColor.r*/,
	g: /*WGPURenderPassColorAttachment.clearColor.g*/,
	b: /*WGPURenderPassColorAttachment.clearColor.b*/,
	a: /*WGPURenderPassColorAttachment.clearColor.a*/
}
```

**Comment by kainino0x** [comment]
This could very well be due to an issue in our Vulkan implementation (@austinEng?). Are you able to test on Windows? Agree it's unlikely to be a bindings issue but maybe you could try unconditionally extracting the clearColor just to see if it makes a difference.

I also have an RX 580 (Windows and Linux) so if have a benchmark you can share I'd be happy to investigate it a bit.

**Comment by rcelyte** [comment]
I don't have a Windows install on hand, but I was able to compile both versions of the benchmark to single html files:
[load.html.txt](https://github.com/gpuweb/gpuweb/files/7893495/load.html.txt) | [clear.html.txt](https://github.com/gpuweb/gpuweb/files/7893496/clear.html.txt)   *(GitHub didn't like the .html extension)*

Note that the 'Clear' version only shows the bottom-rightmost viewport, since the texture is cleared before each pass.

**Comment by kainino0x** [comment]
Thanks! Reproduces on my Mac (Intel GPU) so it's at least not specific to Dawn's Vulkan backend. I do wonder if this has anything to do with lazy clearing though.
Unfortunately crashes in Firefox so I can't easily test wgpu.

**Comment by Kangz** [comment]
Clearing is not free on desktop GPUs and loading is actually more efficient because it is only done on demand if the ROP needs to read back the current framebuffer value. It's not clear how we can do better in WebGPU than to just delegate that decision to the app.

**Comment by kainino0x** [comment]
Editors: To land due to no further comment.

**Comment by kainino0x** [comment]
@toji can you resolve the merge conflicts and land?

**Pull request merged**
