### PR TITLE
Fix preview version

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
@dneto0

### CODE REVIEW

**Comment by mehmetoguzderin** [comment]
This issue is caused by the fact that for safety reasons preview publisher only pulls the spec files and does not change the commit, which is luckily patchable.

**Review by dneto0 — APPROVED** [review]
Thanks!

**Review by kainino0x — APPROVED** [review]
huh, didn't even realize those source links were there! Does bikeshed generate them?

**Comment by mehmetoguzderin** [comment]
@kainino0x yes but not with commit which @dneto0 added (very helpful change)

**Pull request merged**
