### PR TITLE
Tweak the description of adapters to not mention accelerators or GPUs explicitly

### PR DESCRIPTION
**Pull request by litherum**
***
<a href="https://pr-preview.s3.amazonaws.com/litherum/gpuweb/pull/2029.html" title="Last updated on Aug 11, 2021, 2:13 AM UTC (91b4317)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/2029/ef3fbc5...litherum:91b4317.html" title="Last updated on Aug 11, 2021, 2:13 AM UTC (91b4317)">Diff</a>

### CODE REVIEW

**Review by kainino0x — COMMENTED** [review]
I think this is a real loss to the usefulness of this sentence, but I would accept something like:

> , including which browser implementation path and underlying GPU hardware (if any) are used.

**Comment by litherum** [comment]
See also: https://github.com/gpuweb/gpuweb/issues/2030

**Review by kvark — COMMENTED** [review]
Avoiding the "accelerator" term seems fine to me. The days of GPUs considered to be "accelerators" are long gone. They are integral part of todays personal computing.

However, with this sentence being more abstract now, it's not clear to me as a reader what the difference is between "compute/rendering functionality" and "WebGPU on top of that functionality".

We need some notion of the underlying platform that we are running on, to make this clear.

**Review by kvark — APPROVED** [review]

**Comment by toji** [comment]
Just to confirm, is the desire to avoid terms like "GPU" in this case limited to the definition of an adapter? The proposed language reads a little awkwardly to me but I think that it's workable if limited to that scope.

Given that the spec is named "WebGPU", however, and every interface/dictionary/enum is prefaced with "GPU", and we frequently need to talk about how features interact with GPU capabilities, it seems intractable to do a larger scale removal of the term.

**Comment by toji** [comment]
> Each adapter identifies both an instance of compute/rendering functionality on a
> platform underlying a browser, and an instance of a browser's implementation of
> WebGPU on top of that functionality.

Trying to think of how to word this in a way that feel more natural to me, maybe something like:

"Each adapter identifies both a platform's method of executing compute and rendering tasks, and an instance of a browser's implementation of WebGPU on top of that platform method."

**Pull request merged**
