### PR TITLE
[wgsl] Minor typo fixes and formatting

### PR DESCRIPTION
**Pull request by frzi**
Minor changes for cleanliness sake. Looking forward to further development of WGSL.

### CODE REVIEW

**Comment by dj2** [comment]
I don't know how long the bot usually takes, or if it's failed in some fashion?

**Comment by Kangz** [comment]
It's normally pretty quick but it's not clear if it is a config issue or a GitHub issue: GitHub has been pretty flaky today.

**Comment by Kangz** [comment]
[Travis hasn't seen the PR yet](https://travis-ci.org/gpuweb/gpuweb/pull_requests?utm_medium=notification&utm_source=github_status).

**Comment by frzi** [comment]
Is there something I need to do on my side to get Travis to recognize the PR?

**Comment by Kangz** [comment]
It seems to be blocked on #563.  Maybe @dj2 can check the PR compile locally and merge until we find a solution.

**Pull request merged**
