### PR TITLE
Add indirect draw / dispatch

### PR DESCRIPTION
**Pull request by iraiter2**
Following the investigation at issue #31, we were able to implement indirect draws in dawn. D3D12 / Vulkan / Metal / OpenGL all use the same format for the indirect commands in memory. The only issue we ran into is in OpenGL index buffers can't be bound with an offset (leading to the offset being ignored in indirect indexed draws). However, this was fixable with a compute pass. We are considering implementing validation using compute shaders for indirect calls, and converting normal calls to indirect ones in order to reuse logic and avoid CPU round trips.

***
<a href="https://pr-preview.s3.amazonaws.com/iraiter2/gpuweb/pull/317.html" title="Last updated on Jun 25, 2019, 10:22 PM UTC (b91d453)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/317/64225b4...iraiter2:b91d453.html" title="Last updated on Jun 25, 2019, 10:22 PM UTC (b91d453)">Diff</a>

### CODE REVIEW

**Comment by kvark** [comment]
Do we have an option of clamping the number of vertices/indices instead of discarding the whole draw call?

**Comment by kainino0x** [comment]
@kvark Possibly, but we're not sure how that would work. Let's discuss further once Idan opens an issue about the topic.

**Comment by grorg** [comment]
Discussed at [25 Jun 2019 teleconference](https://docs.google.com/document/d/1g6Xu3S4WBJWyRN1lyx-YsmTkOcidVWe2WWgsVn2Wq8E/edit#)

**Comment by kainino0x** [comment]
Discussed today. Resolution: Restrict base instance to always be zero (necessary on some Vulkan) for now; then merge. MTLGPUFamilyMac1 does not support indirect draw at all; @litherum will check what devices that includes and we can decide whether it's necessary to move these into an extension.

**Comment by kainino0x** [comment]
Merging per the discussion in the meeting.

**Comment by litherum** [comment]
I checked and we have no objections based on device compatibility.

**Comment by kainino0x** [comment]
Looking back at the feature set tables, I may have misread during the meeting (or maybe the PDF changed?): Indirect draw/dispatch is supported on MTLGPUFamilyMac1.

I looked back at an old copy of the feature set tables I still have downloaded from pre-3.0, and it provides more details (unless it's wrong): Only macOS_GPUFamily1_v1 does not support indirect draw/dispatch. If I'm reading the table correctly, that means all hardware supports it, but that macOS 10.11 does not. So it looks like requiring this means we can't support macOS 10.11. (@Kangz, WDYT of that restriction?)

**Comment by Kangz** [comment]
That's probably ok, but we should check our telemetry data to make sure (I tried but failed to use the site)

**Comment by kainino0x** [comment]
We still have a surprising number of users on 10.11, but it is end-of-lifed, and I strongly suspect that most of those users have hardware that doesn't support Metal at all. Seems OK.

**Pull request merged**
