### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by mehmetoguzderin**

### CODE REVIEW

**Comment by kvark** [comment]
I wonder how long it takes. 10 minutes already.

**Comment by mehmetoguzderin** [comment]
@kvark Yes, I suspect that's because of skipping manifest (in my own dev repo, build went up from less than 1 min to 5 min). Though we can speed that up.

**Comment by kvark** [comment]
It would be helpful to see the commit hash mentioned in this comment. It would instantly let us see if this is latest preview or not.

**Comment by mehmetoguzderin** [comment]
> It would be helpful to see the commit hash mentioned in this comment. It would instantly let us see if this is latest preview or not.

That definitely makes sense, it is actually available as a HTML comment for a potential future bot that would go over these comments. But we can duplicate as a human readable text too.

**Comment by Kangz** [comment]
Does the action post a new comment when a commit or a force-push happens?

**Comment by mehmetoguzderin** [comment]
@Kangz yes, as discussed around this comment: https://github.com/gpuweb/gpuweb/pull/1193#issuecomment-719122972

**Comment by Kangz** [comment]
Great! Sorry I haven't been following too closely.

**Pull request closed without merging**
