### PR TITLE
Fix WGSL grammar flow for Python virtual environments

### PR DESCRIPTION
**Pull request by dneto0**
1. move 'tree-sitter generate' step before npm install.
2. If we're operating in a virtual environment then user site packages are not accessible.  In that case do an ordinary 'pip install' instead of a user-install of the tree-sitter-wgsl package.

### CODE REVIEW

**Review by mehmetoguzderin — APPROVED** [review]
LGTM

**Comment by mehmetoguzderin** [comment]
@dneto0 could you check the CI issue?

**Comment by dneto0** [comment]
> @dneto0 could you check the CI issue?

See https://github.com/gpuweb/gpuweb/issues/4924 

It causes:

>     $ bikeshed --die-on=warning spec "wgsl/index.bs" "wgsl/index.bs.built.html" 
      WARNING: You used Status ED, but your Group (WEBGPU) is limited to the statuses CG-DRAFT, CG-FINAL, or UD.
       ✘  Did not generate, due to errors exceeding the allowed error level.
    Command `bikeshed --die-on=warning spec "wgsl/index.bs" "wgsl/index.bs.built.html" ` failed with exit code: 2.

**Comment by mehmetoguzderin** [comment]
@dneto0 actually there is another error before that:

```
An error happened while installing `tree-sitter-wgsl` in editable mode.
```

**Comment by dneto0** [comment]
> @dneto0 actually there is another error before that:
> 
> ```
> An error happened while installing `tree-sitter-wgsl` in editable mode.
> ```

oops.  I didn't check that flow.... looking

**Pull request merged**
