### PR TITLE
In certain places, identifiers don't resolve to declarations

### PR DESCRIPTION
**Pull request by dneto0**
Define non-resolving context, and specify where they are
    
Fixes: #3113

Reorg declaration and scope
    
    Reorder so we talk about all the kinds of declarations and their
    scopes before talking about resolving an identifier.

### CODE REVIEW

**Comment by dneto0** [comment]
> I think this works, but the nomenclature is odd. Non-resolving contexts do resolve to something, just not traditional declarations.

I had two thoughts:
1.  Rename the section "Name-tokens" and then say a "Name-token" is a token used as a name.  And then reserve "identifier" for *only* the uses that are about declared and predeclared objects.  That seemed super awkward, and a big change.
2. Say "non-declaration-resolving" instead of "non-resolving".  I'll give that a shot.  It's smaller, and more specific.

I also had the idea of using a distinct grammar element for the non-resolving case.  Since the non-resolving contexts are grammar-determined, that should be an uncomplicated and unambiguous change.

**Comment by alan-baker** [comment]
> I also had the idea of using a distinct grammar element for the non-resolving case. Since the non-resolving contexts are grammar-determined, that should be an uncomplicated and unambiguous change.

This sounds interesting to me. It seems obvious for things like texture formats, but I wonder if that means attributes have to be duplicated into the grammar. That would be unfortunate.

**Comment by dneto0** [comment]
> > I also had the idea of using a distinct grammar element for the non-resolving case. Since the non-resolving contexts are grammar-determined, that should be an uncomplicated and unambiguous change.
> 
> This sounds interesting to me. It seems obvious for things like texture formats, but I wonder if that means attributes have to be duplicated into the grammar. That would be unfortunate.

I did this work.   In particular, I introduced new nonterminals so that `ident` is only used for cases where it's a declared object.    Yes, it expands the attribute grammar, but it's worth it.
Also fixed problems with struct member names.

**Review by alan-baker — APPROVED** [review]
This is much clearer to me, thanks.

**Pull request merged**
