### PR TITLE
Remove duplicate grammar rule: global_constant_decl

### PR DESCRIPTION
**Pull request by dneto0**

### CODE REVIEW

**Comment by dneto0** [comment]
cc: @kainino0x

**Comment by dneto0** [comment]
There's already a definition of this rule in 4.2 Module Constants. (and that one has the attributes needed for specialization constants).  Remove the redundant one.

**Comment by litherum** [comment]
I did this, and more, in https://github.com/gpuweb/gpuweb/pull/1054

**Comment by dneto0** [comment]
Closing, as superceded by #1054

**Pull request closed without merging**
