### PR TITLE
Allow SharedArrayBuffer in writeBuffer/writeTexture with AllowSharedBufferSource

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/webidl/pull/1311 for context.

----

This might not pass CI right away, but it should tomorrow.

### CODE REVIEW

**Comment by kainino0x** [comment]
Excellent! I'll close #4187 in favor of this.

**Comment by kainino0x** [comment]
Actually, since it was ambiguous before whether SharedArrayBuffer was supported here (and I believe Chrome doesn't allow it now), I don't think we can call this editorial. I'll retitle.

Also since I think it was the original intent, I'll put this in V1 instead of Milestone 2.

**Review by kainino0x — APPROVED** [review]
LGTM. I think we should make this V1 but open to calling it milestone 2 if implementations won't be trivial.

**Review by mwyrzykowski — APPROVED** [review]

**Comment by kainino0x** [comment]
@kdashg @litherum opinions about calling this V1 and landing it, vs calling it milestone 2 (and going back and making another PR to explicitly exclude SharedArrayBuffer from V1)?

**Comment by kainino0x** [comment]
Chatted with @kdashg and WebGL was already using `[AllowShared] BufferSource` to mean this. So to both of us, this is a non-change in intent (except that Chrome implemented it incorrectly). Since @mwyrzykowski has approved I'm going to go ahead and land this.

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
