### PR TITLE
wgsl: remove unsigned case for frexp 2nd arg

### PR DESCRIPTION
**Pull request by dneto0**
Fixes: #1820

### CODE REVIEW

**Comment by dneto0** [comment]
I've anticipated consensus.
The group needs to review the decision first.

**Review by alan-baker — APPROVED** [review]

**Review by kvark — APPROVED** [review]

**Comment by dneto0** [comment]
I updated the PR to also remove the unsigned case for the 2nd arg of ldexp, as proposed in #1820

**Comment by dneto0** [comment]
Approved in 2021-06-15

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-15-Minutes#wgsl-remove-unsigned-case-for-frexp-2nd-arg-1823">WGSL meeting minutes 2021-06-15</a></summary>



*   Issue: [wgsl: frexp: what happens if the exponent is negative but the second operand is ptr-to-u32 #1820](https://github.com/gpuweb/gpuweb/issues/1820)
*   (Propose dropping the unsigned case for second arg to frexp and ldexp)
*   MM: Why outvars?
*   DN: We don’t have tuples and don’t have named structs yet
*   JG: I think proposing struct names was on me
*   (merge this though)


</details>

**Pull request merged**
