### PR TITLE
"gpu" is not a valid canvas context type; "gpupresent" is

### PR DESCRIPTION
**Pull request by jameshfisher**
Tested on Google Chrome 82.0.4073.0 (Official Build) canary (64-bit)

### CODE REVIEW

**Comment by othermaciej** [comment]
Does the spec define what the context type should be yet? I couldn't find this defined in the WebGPU spec (or the HTML spec for that matter).

**Comment by kvark** [comment]
WebGL [does](https://www.khronos.org/registry/webgl/specs/latest/2.0/#2.1). If we don't specify this, it would be hard to host any examples and tests that run portably.

**Comment by magcius** [comment]
`gpupresent` was unofficially voted on here, which is why Chrome uses it: https://github.com/gpuweb/gpuweb/issues/131

**Comment by othermaciej** [comment]
I mean, we obviously need to specify it, but we currently don't, right? Is there an open issue? Until this is decided it's not possible to make interoperable test cases, which seems like a problem. It's also not possible any context value is incorrect or that another is more correct, which I think makes this PR invalid? Unless browsers already de facto match.

(For WebGL, this is specified both in the WebGL spec, as cited, and [in the HTML spec](https://html.spec.whatwg.org/#dom-canvas-getcontext).)

**Comment by othermaciej** [comment]
> `gpupresent` was unofficially voted on here, which is why Chrome uses it: #131

It's hard to tell if that unofficial vote was an official CG decision or not (seems like no?) but in any case the reason for it seems to be invalid. WebXR no longer has an "xrpresent" context, so being consistent with it is not a consideration. (In fact it has no canvas context defined at all, but when it last did, that context was called "present-xr"). I left that info in a comment on the (closed) issue.

**Comment by kvark** [comment]
I believe we as a group agreed on `gpupresent`, which would make this PR totally valid (considering that the spec itself is WIP). However, the new information by @othermaciej looks convincing to me to reconsider this (thanks!).

**Comment by Kangz** [comment]
`"gpupresent"` was agreed upon in this [meeting](https://docs.google.com/document/d/1yYuZHcWo98_4P9S-GBN_LQVARUKEovvJTMaCLxehXqU) based on #131 but we can revisit the decision if we want to in light `"xrpresent"` not being a thing anymore. Thanks @othermaciej for the head's up.

**Comment by kainino0x** [comment]
From meeting: We should pick a phrase and then go to the HTML spec folks for the casing/hyphenation issue.

**Comment by kainino0x** [comment]
[pr cleanup] There's no reason to keep this open, we have #131 for this topic.

**Pull request closed without merging**
