### PR TITLE
Make imageHeight optional

### PR DESCRIPTION
**Pull request by kainino0x**
It's [awkward](https://github.com/gpuweb/cts/pull/95/files#diff-d79e5d51a5b1c3e1d586625d3f7aff62R77) to have to specify an `imageHeight` when you're not doing an array/3d texture copy (i.e. almost always).
Make it default to 0 - and I'd have this be valid unless `copySize.depth > 1`.

... also, I still don't really like the name "imageHeight"...

***
<a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/pull/517.html" title="Last updated on Mar 9, 2020, 10:17 PM UTC (1f0c902)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/517/da1d4f8...1f0c902.html" title="Last updated on Mar 9, 2020, 10:17 PM UTC (1f0c902)">Diff</a>

### CODE REVIEW

**Comment by kainino0x** [comment]
Done (sketchily)

**Comment by jdashg** [comment]
I think I like having 0 indicate tightly-packed src, a la GL. No strong feelings, but I think that's easier to use.

**Comment by kainino0x** [comment]
I'm pretty neutral, leaning very slightly toward "0 is only valid if unused".

**Comment by Kangz** [comment]
This was discussed in the [2020-01-06 meeting](https://docs.google.com/document/d/1nESeFHsqOgBxG-vM19THWGf_C6G6fVrxj16PXuaE47Q)

**Comment by kainino0x** [comment]
Resolution: update to make 0 mean tightly-packeg

**Comment by kainino0x** [comment]
Discussed today. Given #537, I would advocate to land this PR as-is, instead of trying to encode that limitation into the definition of "tightly packed". @jdashg @kvark any objections?

**Comment by grorg** [comment]
Discussed again at the [2020-02-03 teleconference](https://docs.google.com/document/d/1R0soTTyT5hTCrLxwwEJ16Q1kungybPth6nSsRXXu8t0/)

**Comment by kainino0x** [comment]
Let's talk about this at the F2F:
Should we make imagePitch=0 (and even rowPitch=0) really, semantically mean 0? I.e. the same data would be copied into every (layer/slice, row, respectively).

action item @kainino0x: look up whether any native APIs allow this.

**Comment by kainino0x** [comment]
Another alternative is to make 0 just mean "naively tightly packed", and error if that violates other restrictions. I *think*(?) that's what Vulkan does.

**Comment by kainino0x** [comment]
Done: https://github.com/gpuweb/gpuweb/pull/519#issuecomment-581676068

**Comment by kainino0x** [comment]
Discussed at F2F. To be resolved by spec editors.

**Comment by kainino0x** [comment]
Actually, this particular item was resolved at the F2F. Updated and landing, then I'll do the rest of it as another PR.

**Pull request merged**
