### PR TITLE
Use COPY instead of TRANSFER for GPUBufferUsage and GPUTextureUsage

### PR DESCRIPTION
**Pull request by beaufortfrancois**
GPUBufferUsage `TRANSFER_SRC` and `TRANSFER_DST` and GPUTextureUsage `TRANSFER_SRC` and `TRANSFER_DST`  seem to be used only for `GPUCommandEncoder.copyX` operations such as `copyBufferToBuffer`, `copyBufferToTexture`, `copyTextureToBuffer`, and `copyTextureToTexture`.

How about making it renaming them to `COPY_SRC` and `COPY_DST` for  consistency?

***
<a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/pull/342.html" title="Last updated on Jun 26, 2019, 5:28 AM UTC (d406a75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/342/37e0cfb...d406a75.html" title="Last updated on Jun 26, 2019, 5:28 AM UTC (d406a75)">Diff</a>

### CODE REVIEW

**Comment by Kangz** [comment]
Can you also update the examples that are presented in some of the explainers? BufferOperations.md has some references to these enums.

**Comment by beaufortfrancois** [comment]
> Can you also update the examples that are presented in some of the explainers? BufferOperations.md has some references to these enums.

Done.

**Comment by kvark** [comment]
That makes sense to me. The only thing not clear is how will the possible new commands fit into this usage, such as `fillbuffer` or `clearTexture`

**Comment by Kangz** [comment]
@kvark good point. That said we don't have these function at this time and they can also be seen as copies.

@RafaelCintron @jdashg @litherum PTAL

**Pull request merged**
