### PR TITLE
[editorial] Fix logo's

### PR DESCRIPTION
**Pull request by munrocket**
Continuing #3352

### CODE REVIEW

**Review by toji — APPROVED** [review]
Thank you for addressing the gaps in the SVG! These all appear to me to be a visual improvement over the previous versions, so I'm happy with them.

**Review by kainino0x — CHANGES_REQUESTED** [review]
I do think this is an improvement, but as rendered in Chrome/Firefox/Safari on my machine there are still little artifacts here and there:
image
image
image

Inkscape shows why:
image

I'd do one of two things. Either set (maybe .5px) strokes on all triangles and use `stroke-linejoin: round` so they line up perfectly:
image

or make them actually overlap:
image

Finally, there are still some alignment issues which are making the gap worse. This one is seen in webgpu-notext.svg (zoomed to 25600%):

image

**Comment by kainino0x** [comment]
Having the shapes overlap seems to be the most robust. Even a 1px stroke disappears and the gap artifact slightly returns when you scale so that that's smaller than 1 screen pixel.

**Review by munrocket — COMMENTED** [review]
Sorry for so long review. Looks like this is the first time when I am review suggested changes. 🥹

**Review by kainino0x — APPROVED** [review]
Great! I think there are still some tiny nits we could improve someday if we want (slight oddities at corners due to the stroke), but these are concretely better - I'm seeing no gaps between triangles at various resolutions which is much nicer!

**Pull request merged**
