### PR TITLE
Make GPUShaderModuleCompilationHint.layout optional

### PR DESCRIPTION
**Pull request by Kangz**
Issue #2574 shows that we may want to add more information to hints in
the future. To help make the hints future-proof, the layout is made
optional so that authors can in the future pass information like the
primitive type, even if they don't know what the pipeline layout will
be.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 12, 2022, 3:22 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FKangz%2Fgpuweb%2Ffb70242129251250d749ee032355f87f32bf1618%2Fspec%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20gpuweb/gpuweb%232876.)._
</details>

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
LGTM. I think this change isn't _strictly_ necessary because we can always make it optional later when we add other fields. But the clear benefit to making it optional now is that future applications won't have to do nasty feature detection or UA detection for older browsers that require this field.

**Comment by toji** [comment]
LGTM as well, seems like a good future-proofing strategy.

**Comment by juj** [comment]
Does omitting `layout` mean the same as having passed `layout: 'auto'`?

**Comment by toji** [comment]
No, it doesn't. And that's intentional.

As it turns out, using the `auto` layout is relatively limiting and probably not the pattern that most developers want to reach for instinctively. It can be a nice shortcut _if_ you know that you won't need the same layout anywhere else, but we wanted that to be an intentional decision on the part of the developer and not the default.

So now you always have to specify a layout, and can explicitly choose `auto` if that's what you need. The hope is that doing things this way helps nudge developers towards better practices.

**Comment by juj** [comment]
Thanks - the reason I am asking is that when marshalling over to wasm, handwritten JS code could specify any type of hint object of form:
  - `null` (i.e. no hint object specified at all)
  - `{ }`,
  - `{ layout: null }`,
  - `{ layout: undefined }`,
  - `{ layout: 'auto' }`
so I am trying to figure out what type of polymorphic expressiveness here is needed for wasm side programs to be able to pass. The four first ones are quite reasonably the same thing, but then wondering if wasm code should be able to say `{ layout: 'auto'}` as well, or if that case could be handled statically as one of the above four cases.

**Comment by kainino0x** [comment]
I filed https://github.com/webgpu-native/webgpu-headers/issues/166 .

**Pull request merged**
