### PR TITLE
Allow inter-stage variable subsetting

### LINKED ISSUE #2038: Shader stage input-output subsetting rules
Is it possible for the vertex shader to only use a subset of the vertex attributes hooked up by the API?

Is it possible for the fragment shader to only use a subset of the attribute data the vertex shader outputs?

It seems that this is something that an author would naturally want to be able to do. @kenrussell even described during today's call how he's found that many authors want to do these things. Let's see if it's possible.

### PR DESCRIPTION
**Pull request by kainino0x**
**Proposed** less strict alternative to #3073

Fixes #2038

### CODE REVIEW

**Review by Kangz — APPROVED** [review]
LGTM assuming the group approves.

**Comment by kainino0x** [comment]
Approach approved in CG meeting 2022-07-13

**Comment by kainino0x** [comment]
Which I suppose means we land this.

**Comment by lokokung** [comment]
Removing 'needs-cts-issue' since there is already an open CTS issue: https://github.com/gpuweb/cts/issues/1554

**Pull request merged**
