### PR TITLE
Decrease the minimum required maxTextureArrayLayers to 256

### PR DESCRIPTION
**Pull request by Kangz**
The previous value of 2048 was preventing WebGPU from being supported on
any ARM Android devices.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 24, 2021, 11:22 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FKangz%2Fgpuweb%2F42ea075e26f784d765708ac59b226a7fc851b730%2Fspec%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20gpuweb/gpuweb%232059.)._
</details>

### CODE REVIEW

**Comment by Kangz** [comment]
See #513

**Comment by fintelia** [comment]
The [previous analysis](https://github.com/gpuweb/gpuweb/issues/1327#issuecomment-754958137) was that the most prominent/recent devices that didn't meet the limit were from 2016-2017. Is that no longer true?

**Comment by Kangz** [comment]
The previous analysis must have been wrong since all ARM devices only support 256. There are new ARM devices shipped all the time.

**Review by kvark — APPROVED** [review]
Well, if that's the case... 😢

**Review by kainino0x — APPROVED** [review]
I went back and checked gpuinfo and this checks out - no ARM has 2048. (From inspection it seems Mali-T880 and Mali-G72 are still the most popular, but they are probably also still current designs even though they're a few years old.)

**Comment by kainino0x** [comment]
And very recent ARM devices bump this to only 1024.

**Pull request merged**
