### PR TITLE
Updating for loops spec

### PR DESCRIPTION
**Pull request by ponitka**

### CODE REVIEW

**Comment by ponitka** [comment]
Somebody has to add the wgsl label for me, because I don't think I can do it myself :/

**Comment by tidoust** [comment]
@ponitka, IPR bot complains because it does not know anything about you. I suspect you might be affiliated with Google. If so, the complaint can be safely ignored and I'll let you check with @Kangz whether it makes sense for you to create a W3C account and join the CG/WG so that the IPR bot can successfully identify you in the future.

**Comment by ponitka** [comment]
Yes, I work at Google and my Github account is linked to my work address, not to W3C account though. There were no issues with my PRs about a month ago, so I guess this bot is a new thing.

**Comment by tidoust** [comment]
> Yes, I work at Google and my Github account is linked to my work address, not to W3C account though. There were no issues with my PRs about a month ago, so I guess this bot is a new thing.

Indeed, that's new, linked to the recent creation of the GPU for the Web Working Group. See [message I sent to the CG/WG](https://lists.w3.org/Archives/Public/public-gpu/2020Aug/0003.html). The goal of the IPR bot is not to be a pain, although enabling it unfortunately creates a bit of a nuisance initially, but rather to let you all work on the technical contents of the specs without having to worry about IPR issues, while reassuring your companies that usually care about IPR issues that there are no such issues to worry about...

**Comment by dj2** [comment]
@dneto0 any comments?

**Comment by grorg** [comment]
> Yes, I work at Google and my Github account is linked to my work address, not to W3C account though. There were no issues with my PRs about a month ago, so I guess this bot is a new thing.

It's fairly easy to go to the W3C site and let it know what your github username is.
https://www.w3.org/users/myprofile/connectedaccounts

**Review by grorg — APPROVED** [review]

**Pull request merged**
