### PR TITLE
Unpack builtins

### LINKED ISSUE #988: Support pack / unpack functions
To implement vertex pulling, we need to bind vertex buffers as flat storage buffers, for example:
[[binding 0, set 0]] var<storage_buffer> vertexBuffer0 : [[block]] struct {
  [[offset 0]] bufferData : [[stride 4]] array<u32>;
};

Then, reading from the buffer, we can obtain chunks of 4 bytes through the u32 bufferData. Currently, we would be able to read floats using "as\<f32\>(data)", and vectors by repeated reads.

The reason we need this is because attributes can refer to the same section of the buffer with different types, or have alignment problems (the alternative would be to try to generate some struct type which runs into these problems).

To be able to support vertex input formats such as "half" we need functions to unpack them, and probably include packing for consistency. These are available in GLSL std 450 under the following names:
PackSnorm4x8
PackUnorm4x8
PackSnorm2x16
PackUnorm2x16
PackHalf2x16
PackDouble2x32

UnpackSnorm4x8
UnpackUnorm4x8
UnpackSnorm2x16
UnpackUnorm2x16
UnpackHalf2x16
UnpackDouble2x32

Is there anything we need to add or would this be covered by importing GLSL.std.450? Should these be WGSL functions usable without an import?

### PR DESCRIPTION
**Pull request by dneto0**
Builds on #1189, so review that first.

Fixes #988

### CODE REVIEW

**Comment by dneto0** [comment]
HTML preview is at https://gistpreview.github.io/?f0ddc91317e4d58e526ecd0a5528ce95

**Review by dj2 — APPROVED** [review]

**Review by kvark — APPROVED** [review]
LGTM, minus the comments to the base PR

**Comment by grorg** [comment]
Discussed at [2020-11-03 meeting](https://docs.google.com/document/d/1oV6pmwFOcomeuInQRl-erFt6ZiQfApXYSjoJis7zetA/).

**Review by jdashg — APPROVED** [review]

**Comment by grorg** [comment]
Resolution: Accepted!

**Comment by dneto0** [comment]
In the meeting I made a mistake. I had claimed these all had direct support in all the backends.
They do in Vulkan and Metal, but not HLSL. 

For the *pack* functions, I've written down the translations in this comment: https://github.com/gpuweb/gpuweb/pull/1189#issuecomment-721361704 

For the unpack functions:

- WGSL `unpack4x8snorm( v : u32) -> vec4<f32>`
    - SPIR-V GLSL.std.450 extended instruction UnpackSnorm4x8
    - MSL: unpack_snorm4x8_to_float(v)
    - HLSL:  `max(-1.0, (float4( v&0xff, (v>>8) &0xff, (v>>16)&0xff, (v>>24)&0xff)-float4(127.0))/ 127.0)`


- WGSL `unpack4x8unorm( v : u32) -> vec4<f32>`
    - SPIR-V GLSL.std.450 extended instruction UnpackUnorm4x8
    - MSL: unpack_unorm4x8_to_float(v)
    - HLSL:  ` float4( v&0xff, int((v>>8) &0xff, (v>>16)&0xff, (v>>24)&0xff) / 255.0)`

- WGSL `unpack2x8snorm( v : u32) -> vec2<f32>`
    - SPIR-V GLSL.std.450 extended instruction UnpackSnorm2x16
    - MSL: unpack_snorm2x16_to_float(v)
    - HLSL:  `max(-1.0, (float2( v&0xffff, (v>>16) &0xffff) - float2(32767.0)) / 32767.0)`

- WGSL `unpack2x16unorm( v : u32) -> vec2<f32>`
    - SPIR-V GLSL.std.450 extended instruction UnpackUnorm2x16
    - MSL: unpack_unorm2x16_to_float(v)
    - HLSL:  ` float2(v&0xffff, (v>>16)&0xffff) / 65535.0)`

- WGSL `unpack2x16float( v : u32) -> vec2<f32>`
    - SPIR-V GLSL.std.450 extended instruction UnpackHalf2x16
    - MSL: ` packed_half2 temp = as_type<packed_half2>(v); return float2(temp.x, temp.y);`
   - HLSL:    float2( f16tof32(v & 0xffff), f16tof32( v >> 16) )


(I hope I got the details right.)

**Comment by kvark** [comment]
Hmm, so in HLSL there aren't really builtins for that :/

**Comment by grorg** [comment]
Discussed at the [2020-11-10 meeting](https://docs.google.com/document/d/1QFWUKpCcoLCMGHfJQWJurSPk-9PDcJ1Gc51FSg3_Fr8/).

Resolved: Accept with @dneto0's changes above.

**Comment by dneto0** [comment]
> Resolved: Accept with @dneto0's changes above.

My changes/notes are really implementator's notes.  The behaviour they specify is already describe in the WGSL spec text in the PR.

**Comment by dneto0** [comment]
Rebased

**Comment by magcius** [comment]
> `max(-1.0, (float4( v&0xff, (v>>8) &0xff, (v>>16)&0xff, (v>>24)&0xff)-float4(127.0))/ 127.0)`

Am I misreading this, or is this not right? What you have seems to be a biased representation (that is, 0x00 represents -127.0). SNORM is a two's complement signed representation, where 0x00 represents 0.0.

The simplest way to do this in HLSL correctly, as far as I'm aware, is sign extension: `((v << 24) >> 24) & 0xFF` before the divide.

**Pull request merged**
