### PR TITLE
GPUDevice: s/defaultQueue/queue/

### PR DESCRIPTION
**Pull request by Kangz**
***
<a href="https://pr-preview.s3.amazonaws.com/Kangz/gpuweb/pull/1367.html" title="Last updated on Jan 25, 2021, 5:00 PM UTC (6f3efdd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/1367/1f38d53...Kangz:6f3efdd.html" title="Last updated on Jan 25, 2021, 5:00 PM UTC (6f3efdd)">Diff</a>

### CODE REVIEW

**Comment by kvark** [comment]
What's the motivation for this? Some wording in the PR description would be nice to have.

**Comment by Kangz** [comment]
That's because we have a single queue in WebGPU today, so "default" doesn't mean anything and should be removed.

**Comment by kvark** [comment]
But wouldn't it be better *when* we have multiple queues, to have this one called 'defaultQueue'?

**Comment by Kangz** [comment]
I think it is ok to have the primary queue be called `queue` even in an MQ world because most developers will only use a single queue and won't need to care that there are potentially other queues. In a version of WebGPU without MQ for a while, `defaultQueue` is confusing because there are no other queues.

**Review by kvark — APPROVED** [review]
I suppose we can shape this in a way that all other queues are "additional" or "extra"

**Review by kainino0x — APPROVED** [review]
> I think it is ok to have the primary queue be called `queue` even in an MQ world because most developers will only use a single queue and won't need to care that there are potentially other queues.

this is convincing to me

**Review by toji — APPROVED** [review]

**Pull request merged**
