### PR TITLE
Relax the command encoding validation scope

### PR DESCRIPTION
**Pull request by kvark**
Our implementation validates commands prior to `finish()`. The current specification bit appears to be very Dawn-specific. This PR attempts to relax the time scope for validation.

***
<a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/pull/1021.html" title="Last updated on Aug 21, 2020, 7:18 PM UTC (a8b40ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/1021/f9b2c4d...a8b40ef.html" title="Last updated on Aug 21, 2020, 7:18 PM UTC (a8b40ef)">Diff</a>

### CODE REVIEW

**Comment by kvark** [comment]
@kunalmohan did update Servo in https://github.com/servo/servo/pull/27607 , and it looks feasible to me.
Thinking about the error model in general though makes me a little concerned. The push/pop of the scopes appears to be racing against pretty much anything: buffer mapping, command buffer finishing, submission, etc.

**Comment by Kangz** [comment]
What do you mean with "racing"?

**Comment by kvark** [comment]
There is an implicit dependency between `GPUDevice::pushErrorScope()` and methods on other objects, such as `GPUCommandEncoder::finish()`. What if the encoder is on different worker thread, how do you ensure that the scope is pushed?
In general, we are trying to reduce the implicit dependencies as much as possible, for this reason we have `GPUQueue::writeBuffer` and not `Buffer::setSubData`. We still have one case of a dependency between `GPUBuffer.mapAsync` and `GPUQueue.submit` though.

**Comment by Kangz** [comment]
We haven't discussed about this, but the error scope will probably need to be per-worker. That's fine.

**Comment by kainino0x** [comment]
Yes, the plan is for it to be per-worker. Races would be really bad.

I think how this will work in the spec is that the issuing content-timeline's error scope stack will be "captured" before issuing work to other threads, so when there's an error we know which one to send it back to.

**Comment by grorg** [comment]
Discussed at the [2020-08-24 meeting](https://docs.google.com/document/d/1xKHeGs7d8KOjNPQuRIGYptXacITV9iVNhUTMoOGkTqM/edit#).

**Pull request closed without merging**
