### PR TITLE
Link to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by grorg**

### CODE REVIEW

**Comment by magcius** [comment]
You probably want https://github.com/gpuweb/admin/blob/CONTRIBUTING.md. Current link is a 404

**Comment by kvark** [comment]
Any reason not to use the local paths there?

**Comment by kainino0x** [comment]
The file is in gpuweb/admin rather than gpuweb/gpuweb; can you use a local path to link between the repos?

**Comment by kvark** [comment]
@kainino0x ah right, I see. That's a good reason :)

**Comment by Kangz** [comment]
LGTM with the fix for the 404

**Comment by grorg** [comment]
uugh.

**Pull request merged**
