### PR TITLE
Update pull request preview action.

### PR DESCRIPTION
**Pull request by dj2**
This CL updates the pull request preview to install mermaid and
generate diagrams.

### CODE REVIEW

**Review by kainino0x — APPROVED** [review]
This looks fine, but if the diagrams need regeneration then the build check is going to fail anyway. The build requires diagrams to be pregenerated and checked in, so that people can still build the spec without installing mermaid.

**Comment by dj2** [comment]
Hm, maybe this isn't needed? On one of the PRs I was looking at the preview stopped generating 7 days ago. (Although it _did_ generate on this PR). Has the preview been working on the API side?

**Comment by kainino0x** [comment]
The previewing breaks from time to time because it reaches some quota of uploads to Firebase. It's dumb because we're using a [prebuilt PR preview component](https://github.com/marketplace/actions/deploy-to-firebase-hosting) from Firebase but it runs against these quotas really quickly. We tried getting Firebase people to do something about it but it never happened.

I think @mehmetoguzderin had an idea to get away from this problem but hasn't had a chance to investigate it.

**Comment by mehmetoguzderin** [comment]
@kainino0x is right, I'll bring in a better way to do previews and break the dependency!

**Comment by dj2** [comment]
K, in that case I'm going to close this. Thanks for the info.

**Pull request closed without merging**
