### PR TITLE
Allow indirection

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
This PR allows indirection expressions inside assignment statements.

### CODE REVIEW

**Comment by kvark** [comment]
This is a bit problematic. Grammar defines what code can be written, and we don't want people to write `ref`.

**Comment by mehmetoguzderin** [comment]
@kvark Maybe regarding reference, this PR should just add token to the list and not allow in grammar? Would that fit?

**Comment by ben-clayton** [comment]
Why should we need the token in the list? `ref` is an internal concept. It really does not exist in the grammar in any way.

**Comment by mehmetoguzderin** [comment]
@ben-clayton got it, removed that line too and changed PR to allow indirection (in a way that'll allow CI, maybe further refinement can follow up later).

**Review by kvark — APPROVED** [review]

**Review by dneto0 — CHANGES_REQUESTED** [review]
I'm a little concerned this introduces an ambiguity with:

     unary_expression:
           | singular_expression
           | STAR unary_expression

Maybe it would be better to update the LHS of the assignment_statement to be  unary_expression.

Then you could support chains of *&:

       *&*&v  = 1;

That would be kind of useless but valid.

**Comment by dneto0** [comment]
Investigated a bit further.

Tint has this in its parser:
```
// assignment_stmt
//   : unary_expression EQUAL logical_or_expression
```
So disagrees with WGSL, but I think it's because the WGSL spec is wrong.

And it parses this just fine:
```
[[block]] struct B {
  a: i32;
};

[[group(0), binding(0)]]
var<storage,read_write> b: B;


[[stage(fragment)]]
fn main() -> [[location(0)]] vec4<f32> {
   let p = &b.a;
   *p = 1;
   return vec4<f32>();
}

```

**Comment by mehmetoguzderin** [comment]
@dneto0 Thank you for the direction, there were a few options and I kinda did a blunt one- does the latest commit look better?

**Comment by mehmetoguzderin** [comment]
Oops nope, the commit is bad

**Review by dneto0 — APPROVED** [review]
Looks good to me!

(I'm a little sad that the explanatory text exists in the grammar rule section. We will fix that in another MR.)

**Comment by dneto0** [comment]
Hey @kvark  please confirm you still approve.  I think this can be merged without group review.

**Pull request merged**
