### PR TITLE
Replace error_monad_timeline_diagram's PNG with an SVG

### PR DESCRIPTION
**Pull request by Kangz**

### CODE REVIEW

**Review by kvark — COMMENTED** [review]
Don't you want to fix the link to it as well?

**Comment by Kangz** [comment]
Fix the link?

**Comment by kvark** [comment]
Yes, [the link](https://github.com/gpuweb/gpuweb/blob/5f5917daa4056c5e6e4b88448b0dab19a50de05e/explainer/index.bs#L82)

**Comment by Kangz** [comment]
Ah I must have forgotten to  git add explainer/index.bs

**Review by kvark — APPROVED** [review]

**Comment by kainino0x** [comment]
Just realized the image (both PNG and SVG) are 404 on GitHub pages. oops. I can fix that.

**Pull request merged**
