### PR TITLE
Remove Bit/Bits from bitmasks

### PR DESCRIPTION
**Pull request by Kangz**
***
<a href="https://pr-preview.s3.amazonaws.com/Kangz/gpuweb/pull/292.html" title="Last updated on Jul 9, 2019, 8:12 AM UTC (f129668)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/292/f565f88...Kangz:f129668.html" title="Last updated on Jul 9, 2019, 8:12 AM UTC (f129668)">Diff</a>

### CODE REVIEW

**Comment by Kangz** [comment]
@RafaelCintron @litherum @JusSn can I get an extra review?

**Comment by jdashg** [comment]
What's the reasoning here?

**Comment by jdashg** [comment]
I'll make a PR to instead consistently use FooBit[s]/FooFlag[s].

**Comment by jdashg** [comment]
Please rebase!

**Comment by Kangz** [comment]
Merging this as was discussed in yesterday's call.

**Pull request merged**
