### PR TITLE
If any vertex is OOB, the whole draw call may behave as OOB

### LINKED ISSUE #4668: Allow all vertex input attributes to be considered OOB if at least one is (in the "process vertices" algorithm)
Vulkan without `robustBufferAccess2` behaves this way and we'd also like to do this in our vertex pulling approach for Metal.

> Further, if any vertex input attribute using a specific vertex input binding is out of bounds, then all vertex input attributes using that vertex input binding for that vertex shader invocation are considered out of bounds.

_from https://github.com/KhronosGroup/Vulkan-Docs/blob/ce03761fd6cc1ab8f54c9f785fffb13f492d7d04/chapters/features.adoc?plain=1#L362-L364_

### PR DESCRIPTION
**Pull request by kainino0x**
Fixes #4668

### CODE REVIEW

**Comment by teoxoy** [comment]
This seems to remove the old behavior where implementations were allowed to still load the values that were not OOB for a given attribute even if later attributes will be OOB.

We are ok with this since we don't rely on this behavior but I don't think it was discussed previously. Do dawn/safari need the old behavior? cc @mwyrzykowski

**Comment by Kangz** [comment]
I believe that:

> 1. Load the attribute |data| according to WGSL's [=invalid memory reference=] behavior, from |vertexBuffer|.

allows the previous behavior as the WGSL invalid memory reference could return anything that's in the buffer.

**Comment by teoxoy** [comment]
Oh, I see.

**Review by teoxoy — APPROVED** [review]

**Review by mwyrzykowski — APPROVED** [review]
Sounds good, this is what we are doing  already

**Comment by kainino0x** [comment]
> allows the previous behavior as the WGSL invalid memory reference could return anything that's in the buffer.

I will add a note about this and land it.

**Pull request merged**
