### PR TITLE
Validate IDL with now.sh

### PR DESCRIPTION
**Pull request by darknoon**
This runs IDL validation in a `Dockerfile` on Zeit's now.js service.

happy to change:
- CI service used
- Folder everything is placed in (Dockerfile might need to be in root)

I personally use this for my site so I knew how to set the Dockerfile (just outputs a text file to `public/`), but I'd be happy to switch it to another CI service as appropriate.

Should be fine on the free tier https://zeit.co/pricing

### CODE REVIEW

**Comment by darknoon** [comment]
This an example of one of the builds created. It just runs a static server showing a the static `.txt` file with the result:
https://gpuweb-ncjgqgouwd.now.sh

Zeit now should comment on this PR to link to the build, not sure why it hasn't happened.

**Comment by kvark** [comment]
Thank you for tackling this important infrastructure issue, @darknoon!

I'm not in a good position to review the code, it's too far from my domains of expertise.

I do wonder though, would it be possible to use the more traditional CI like Travis, which would have proper integration with Github (to avoid going to that auto-generated page)?

**Comment by darknoon** [comment]
@kvark It should be commenting on this PR about the build status, I think I might have misconfigured something or the now integration needs to be enabled on `gpuweb` account. Let me test and get back to you.

**Comment by beaufortfrancois** [comment]
I think we can close this one as we now have Travis CI support: https://github.com/gpuweb/gpuweb/pull/334

**Pull request closed without merging**
