### PR TITLE
Draft of WebGPU specification

### PR DESCRIPTION
**Pull request by grorg**
Create a draft specification and move all the sketch.idl content
into it.

The specification is authored using Bikeshed.

### CODE REVIEW

**Comment by grorg** [comment]
Discussed at [25 March teleconference](https://docs.google.com/document/d/1vDcZYv8dfJI-Rilbqc_4OJKjWhzDUPNdoa0dp_TGssc/edit)

- remove space in "Web GPU"
- remove generated HTML
- send PRs for Bikeshed on template and IDL processing
- produce a standalone IDL file

**Comment by grorg** [comment]
I think this is ready to merge now. I've incorporated all the IDL changes up to @kainino0x 9d8a450

**Comment by grorg** [comment]
Oh, I definitely was going to squash + merge :)

**Comment by kvark** [comment]
Do we have to vendor both the bikeshed and the IDL versions of the spec? Since IDL can be generated with `make`, can we avoid versioning it independently?

**Comment by grorg** [comment]
Yeah - we should only generate it. I didn't mean to include it in this patch.

**Pull request merged**
