### PR TITLE
[wgsl] Add stride array decoration.

### PR DESCRIPTION
**Pull request by dj2**
This CL adds the stride decoration to type alias'd arrays.

Issue #773

### CODE REVIEW

**Comment by dneto0** [comment]
> I suppose the spec has to say somewhere that this decoration is required on any host-accessed arrays?

I agree. There's a section to be written about layouts being required on types describing data shared with the host.

For this PR, I recommend modifying the host-shareable section to update the array entry:

> * [[#array-types]] if the array type has a `stride` attribute and its element type is host-shareable

**Comment by dj2** [comment]
Updated host-shareable section.

**Comment by dneto0** [comment]
LGTM.   May get a rework when we add the layout description.

**Comment by grorg** [comment]
Discussed at the [2020-07-14 meeting](https://docs.google.com/document/d/1vBgQ8MDch3-G5LUhrKAE3K2KYeuD5NjGnugCGv0tnVg/).

**Comment by dj2** [comment]
Discussed at the [WGSL 2020-07-21 meeting](https://docs.google.com/document/d/17mqJR40z325U_jftDBxOYAjbzdFxKCQiIUXDEI8d9k4/edit#heading=h.1gfbnysf5cku). I'll try moving the stride decoration into the `type_decl` of the grammar so that you are no longer required to typedef all arrays with strides.

**Comment by dj2** [comment]
Ok, I've updated to move the stride into the `type_decl`. There are a few places where `type_decl` is used where stride would be weird `cast<[[stride 16]]array<f32, 4>>` but still kind of makes sense. `sampled_texture_type` is another, but I'm guessing that's going to have other validations on what the type can be in there anyway.

**Comment by kvark** [comment]
Withdrawing my review as I got concerns expressed in https://github.com/gpuweb/gpuweb/issues/922#issuecomment-662681553 . Maybe I just need to learn more stuff 😅

**Comment by grorg** [comment]
Discussed at the [2020-07-28 meeting](https://docs.google.com/document/d/1Ai4Tgm0PKBln2YjDywmcWQ2QyhIyuwNzWLkbnQr_jdo/).

**Pull request merged**
