### PR TITLE
Add default for arguments of draw and drawIndirect.

### PR DESCRIPTION
**Pull request by Kangz**
***
<a href="https://pr-preview.s3.amazonaws.com/Kangz/gpuweb/pull/632.html" title="Last updated on Mar 30, 2020, 9:23 PM UTC (f3f5dec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/632/c4b3bca...Kangz:f3f5dec.html" title="Last updated on Mar 30, 2020, 9:23 PM UTC (f3f5dec)">Diff</a>

### CODE REVIEW

**Comment by JusSn** [comment]
CI needs an update to python 3??

**Comment by kainino0x** [comment]
Yeah, we need to fix that. Announcement here: https://github.com/tabatkins/bikeshed/issues/321
I think @jdashg was looking at it?

**Comment by jdashg** [comment]
Please rebase after #633

**Comment by kvark** [comment]
>FATAL ERROR: IDL SYNTAX ERROR LINE: 8 - skipped: "void draw(GPUSize32 vertexCount, GPUSize32 instanceCount = 1,
>              GPUSize32 firstVertex = 0, GPUSize32 firstInstance = 0)"

**Comment by kainino0x** [comment]
I think it needs "optional" on all the args.

**Pull request merged**
