### PR TITLE
Use new IDL constructor syntax

### PR DESCRIPTION
**Pull request by romandev**
See heycam/webidl#778.

***
<a href="https://pr-preview.s3.amazonaws.com/romandev/gpuweb/pull/436.html" title="Last updated on Sep 15, 2019, 4:23 AM UTC (15b82cc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/gpuweb/gpuweb/436/51d3fbc...romandev:15b82cc.html" title="Last updated on Sep 15, 2019, 4:23 AM UTC (15b82cc)">Diff</a>

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
I'm not sure what is causing `WARNING: Multiple elements have the same ID 'dom-gpuvalidationerror-message'.` bikeshed error.

**Comment by kainino0x** [comment]
At cursory inspection it sounds like a problem in Bikeshed where it generates the same hash name for both of the following entries:

- `message` argument of `constructor(DOMString message);`
- `readonly attribute DOMString message;`

@romandev any idea what's going on here?

**Comment by beaufortfrancois** [comment]
This is a known bikeshed issue. See https://github.com/tabatkins/bikeshed/issues/1519
Let's merge this PR when bikeshed is updated.

**Comment by kainino0x** [comment]
I found that issue but I'm not sure it's the same - it doesn't describe a name collision like this one. But they're related enough, so hopefully this problem gets fixed when that's done.

**Comment by tabatkins** [comment]
Bikeshed fix is in, let me know if there are any problems.

**Comment by tabatkins** [comment]
(the name collision was indeed a technically separate issue; widlparser was miscategorizing the argument's parent)

**Comment by beaufortfrancois** [comment]
Thank you! It is now fixed.

**Comment by kainino0x** [comment]
Thanks!

**Pull request merged**
