### PR TITLE
Fix wgsl spec example

### PR DESCRIPTION
**Pull request by IcanDivideBy0**
WGSL example code is invalid : https://gpuweb.github.io/gpuweb/#example-91243acf

### CODE REVIEW

**Comment by ben-clayton** [comment]
What makes you believe this code sample is invalid?

It compiles with Tint just fine.

**Comment by IcanDivideBy0** [comment]
Regarding [WGSL vectors spec](https://gpuweb.github.io/gpuweb/wgsl/#vector-types) I don't see any reason the component type is inferred nor type alias declated for `vec2` (there is for `vec2f` tho). Also it doesn't compiles with naga.

**Comment by ben-clayton** [comment]
See the `Vector constructor type rules` table in https://gpuweb.github.io/gpuweb/wgsl/#construction-from-components.

> Also it doesn't compiles with naga

I believe naga is behind the spec here.

**Comment by IcanDivideBy0** [comment]
Oops totally missed that, sorry for the noise

**Pull request closed without merging**
