### PR TITLE
Clarify: texture+sampling validation applies to pairs used together in a builtin

### PR DESCRIPTION
**Pull request by dneto0**
Fixed: #4944

### CODE REVIEW

**Comment by dneto0** [comment]
cc: @greggman @Kangz

**Review by Kangz — APPROVED** [review]

**Comment by greggman** [comment]
So FYI, in the WGSL spec there's this

https://gpuweb.github.io/gpuweb/wgsl/#texturesamplecompare

> If the sampler uses bilinear filtering then the returned value is the filtered average of these values, otherwise the comparison result of a single texel is returned.

`textureSampleCompare` only takes depth textures so I guess the sentence above should be removed? Or leave it for someday when depth textures are allowed to be filtered since today the WebGPU spec disallows it.

**Comment by kainino0x** [comment]
Depth textures can definitely be used with filtering `sampler_comparison`. Maybe the spec text needs to explicitly exclude `sampler_comparison` since it only cares about `sampler`.

**Comment by greggman** [comment]
ah, ... hmmm. I think we need a table 

|                 | texture_?d<f32> | texture_depth_?? | 
| --------------- | --------------- | ---------------- |
| sampler `'linear'`  |      bad        |      bad         |
| sampler_comparison `'linear'` |   N/A |      OK          |

correct?

**Comment by kainino0x** [comment]
yeah, that table seems correct. IMO just tweaking the language to specify it includes `sampler` but not `sampler_comparison` is enough though. I'll draft a PR.

(There was a second fix in #4949 but I don't think that one needs any tweak.)

**Pull request merged**
