### PR TITLE
Typing of literals

### PR DESCRIPTION
**Pull request by RobinMorisset**
This is an alternative to #2227.

### Goals
It has the following two properties:
- If every integer literal is suffixed with `u` or `i`, then typing proceeds like currently
- If a program is well-typed, then it is possible to add a `u` or `i` suffix to every integer literal in it without changing its semantics.

The second property is the main difference with #2227, and I consider it very beneficial for the following reasons:
- No need for the compiler to know how to execute all relevant operators and built-in functions on the CPU with a special precision
- The following two programs are always equivalent, which I consider key for refactoring to be sane:
```
let x: f32 = e1 + e2;
let y: f32 = x + e3;
```
and 
```
let y: f32 = (e1 + e2) + e3;
```
With the "IdealReal"/"IdealInteger" approach of #2227, replacing either one of these pieces of code by the other could silently change the value computed, as it can change the precision with which the computation are done. For example, with `e1= 16777216.0` and `e2=e3=1.0`, the first code fragment would return 16777216.0, and the second would return 16777218.0.

### Contents of the PR
My proposal is based on a two-step approach: start by the usual bottom-up type-checking, but allow it to say "I'm not sure" for expressions which contain unsuffixed literals, then have a top-down phase to refine the type of those expressions.

This PR also contains the grammar changes of #2227, and I've also borrowed a long list of examples from it.

### CODE REVIEW

**Comment by ben-clayton** [comment]
Thank you for posting this proposal.

First, an apology - I'm suffering from a heavy cold and I'm not functioning at 100%. I've dumped my thoughts in a rather random pattern here, separating out the brain-context-switches with horizontal lines.

---

I think that having a non-suffixed integer literal (`123`) be a `literal type`, but a non-suffixed floating point literal (`1.23`)  always be `f32` oddly asymmetrical and restrictive for the day we want to support `f16` or `f64`.

---

> The following two programs are always equivalent, which I consider key for refactoring to be sane:

I'm not sure about the importance of this property, and I think your `16777216.0` example is a great example why we **should** use a single high-precision space for performing our compile-time evaluations.

Taking your example, and replacing the `e1`, `e2`, `e3` symbols with their integer-literal values:

```rust
// Placement of parenthesis and the let 'target type' both affect the final value.
let a: f32 = (16777216 + 1) + 1;  // 16777216.0
let b: i32 = (16777216 + 1) + 1;  // 16777218
let c: f32 =  16777216 + (1 + 1); // 16777218.0
let d: i32 =  16777216 + (1 + 1); // 16777218
```

I think the difference in values between `a` and `b`, `c`, `d` here would likely surprise most developers, more so than your original example.

> For example, with e1= 16777216.0 and e2=e3=1.0, the first code fragment would return 16777216.0, and the second would return 16777218.0.

I'm not sure we can guarantee this to be true. As you're declaring these as `let`s, this is run-time-evaluated, and as we're seeing with #2270, the various backends can be very relaxed in their floating-point math.
The [WGSL spec](https://www.w3.org/TR/WGSL/#floating-point-accuracy) states (see the bottom of 12.5.1. Floating Point Accuracy) that reassociation is permitted, so long as it _"is at least as accurate as the original formulation"_. However [there's a long-ongoing discussion](https://github.com/gpuweb/gpuweb/issues/2076#issuecomment-910439170) about whether we can disable fast-math optimizations that would likely violate this rule. I suspect we may need to adjust the spec here once we start writing CTS tests for these cases.

Taking a step back, this re-association difference you've highlighted is just one of many precision-related differences that a developer will experience moving code from run-time to compile-time (or just silicon A to silicon B). Attempting to have compile-time evaluation exactly match the behavior of run-time evaluation seems like a noble, but near-impossible goal, given that the run-time evaluation varies significantly by device. Which is why I question this being _'key for refactoring to be sane'_.

At a minimum, we should require that the compile-time evaluation conforms to the spec'd tolerances, as that's the requirement we set out for run-time-evaluation. #2227 goes well beyond that minimum, and the developer can entirely forget about these types of storage-type quirks and focus on writing a mathematically-correct expression.

---

You're right that with #2270, `y` may be different between these two snippets:

|`let x: f32 = e1 + e2;`<br>`let y: f32 = x + e3;`|`let y: f32 = (e1 + e2) + e3;`|
|-------------------------------------------------|------------------------------|

But you've been explicit in putting the values into `let`s, which are a **runtime** value.
If `let` were `const`, then the two `y` values would be identical (see below).

---

I have concerns about the second (top-down) phase interacting badly with the "constexpr" proposals which allow you to place a compile-time expression into a named variable. While not mentioned in [litherum's proposal](https://github.com/gpuweb/gpuweb/issues/1272#issuecomment-900706631) (which I believe to be the leading proposal so far), I have been assuming that `const` variables would support type inferencing to match `let` and `var`. This proposal makes this troublesome.

Consider:

```rust
const a = 1
const b = a + a + a
const c = b + b + b
let x : i32 = c;
let y : u32 = c;
let z : f32 = c;
```

With #2227, the values for `x`, `y`, `z` can be calculated in a single pass.

With this proposal, this two-step (which I think is actually three-step) makes for non-linear-time resolving:
* [bottom-up] We first propagate `literal type`s from `1` all the way to `c`.
* [top-down] The three different typed `let`s assigned `c` need to propagate their type all the way back down to `1`, branching for each reuse of the `const` variables `a`, `b` and `c`. The algorithmic complexity here can easily explode.
* [bottom-up] We then need to do a third-pass to actually calculate the end result.

Aside from algorithmic complexity, the `16777216` case above also shows that this would cause action-at-a-distance, and some surprising quirks around casting:

```rust
const C = (16777216 + 1) + 1;
...
let a: f32 = C;           // 16777216.0
let b: i32 = C;           // 16777218
let c: f32 = f32(i32(C)); // 16777218.0 (!?)
```

---
> No need for the compiler to know how to execute all relevant operators and built-in functions on the CPU with a special precision

#2227 used the term 'infinite-precision', which we have since agreed should replace with a fixed-precision. Golang guarantees a minimum of 256 bit. As WGSL currently only supports 32-bit data types, I would suspect that we could get away with computing everything in 64-bit, but we might then want to consider bumping this when we support WGSL 64-bit types.

---

Some final thoughts:

I'm very concerned about the complexity (both for compiler performance, and general-readability) of type-inferencing of `const` if we went with this proposal. I think it would be a real shame if we had to drop `const` type inferencing because of this.

Without `const` type inferencing, single-line expressions can require a significant of mental overhead to figure out what's going on - illustrated by the number of steps described in this PR's examples. Pushing everything into 32-bit types means that there are real cases where you do have to concern yourself with the inferred types, which #2227 avoids.

I really feel like [golang's solution to constants](https://www.ardanlabs.com/blog/2014/04/introduction-to-numeric-constants-in-go.html) reduces complexity for both users of the language and compiler-implementation. It removes concerns about how data is represented - you don't have to care about integer overflows / underflows, fp-quantization, it avoids action-at-a-distance, removes mental burden of guess-the-subexpression-type, allows type-inferencing for `const` in a single pass, all without multiple up-down passes.

**Comment by dneto0** [comment]
I haven't had time to review this in detail.

Another question for me is: what happens when we want to have literals for larger-than-32-bit types?
See #1986

**Comment by jdashg** [comment]
It's difficult when discussing multiple proposals, but let's aim for compare-and-contrast to happen in comments under #2227.
Clarifications can stay here though!

**Comment by dneto0** [comment]
If I understand the proposal correctly, the following program is invalid:

```rust
let i = -2147483648;
```

Why:
- No definite overload is enforced by expression type rules, so the fallback is to assign the literal `2147483648` to type i32.
- But 2147483648 is not representable in i32, which generates a shader-creation error.

**Comment by tex3d** [comment]
I think it could be useful to add a note about a problematic case with special constant literal types: bit-shift operators `<<`, `>>`.

The type of expression for these should be entirely dependent on the left hand side of the operator.  If the left-hand-side of the operator is a literal type, but the right is not, then what operation type is chosen?  This is even more problematic for shift right than shift left, since you may or may not want sign-extend even for some default bit-width.

It's not uncommon to put a shift left expression in the LHS of a shift right expression, and for the original type-deciding expression to be a literal, like `1`.  Ex. `(1 << a) >> b`.  In this expression the `1` is supposed to determine the type for each of these non-literal operations (of course a real example could be less trivial with the same problem).

Since HLSL has special literal types, this was an ambiguous case, and FXC has some odd behavior around it.  For DXC, more recently, we introduced a warning when you don't specify a concrete type for the LHS of the bit-shift operator (Ex. use `(1u << a) >> b` instead).

Note: the HLSL special literal type is not (virtually) unlimited precision: it's a 64-bit signed integer, or 64-bit double for floating point.

**Comment by kdashg** [comment]
Consensus is to go with #2227: https://github.com/gpuweb/gpuweb/pull/2227#issuecomment-1011315038

**Pull request closed without merging**
